### ISSUE TITLE
[Mod]: JFA

### ISSUE THREAD

**Issue by D4RKN3R** [KSP-CKAN/NetKAN#10281]
### Mod Name

JFA

### Author(s)

D4RKN3R

### License

MIT

### Homepage link

https://forum.kerbalspaceprogram.com/topic/223852-jfa-jeb-far-away-1125-alpha-12/

### Download link

https://github.com/D4RKN3R/JFA

**Comment by D4RKN3R** [comment]
"Hey, this is already on CKAN!" I just need it updated and have assumed this is the correct way to do that. I am sorry for the trouble if it isn't, but if so, please direct me to the proper way to do this.

**Comment by SofieBrink** [comment]
I’m not on the ckan team but just gathering information, do you plan to post this release to spacedock too or will you only be using github releases from now on? As that’s what i think reading the release notes

**Comment by D4RKN3R** [comment]
> I’m not on the ckan team but just gathering information, do you plan to post this release to spacedock too or will you only be using github releases from now on? As that’s what i think reading the release notes

It's a spacedock issue. There should be details in the comments of the forum page of the mod. I plan to return to spacedock after it's resolved.

**Comment by HebaruSan** [comment]
Hi @D4RKN3R, sorry for the inconvenicence; this mod has a mysterious inflation error that I haven't been able to figure out yet:

![image](https://github.com/user-attachments/assets/e2521901-d77f-4539-85b7-f0d967bdeb18)

<http://status.ksp-ckan.space/>

![image](https://github.com/user-attachments/assets/c711933c-7a06-4f9e-8d36-747d5552fa9b)

"central directory" most likely means there's something wrong with the ZIP file, but when I downloaded it and inspected it locally, the usual tools for validating ZIP files don't report any issues (otherwise I would have tried to contact you with a recommendation of how to fix it).
 
So I have to try to think of other places to start investigating: Which tools are you using to makethe ZIPs for this mod? Maybe there's some quirk of incompatibility between them and the ZIP library that CKAN uses. If we can figure that out, then maybe we can also figure out a workaround.

**Comment by SofieBrink** [comment]
> > I’m not on the ckan team but just gathering information, do you plan to post this release to spacedock too or will you only be using github releases from now on? As that’s what i think reading the release notes
> 
> It's a spacedock issue. There should be details in the comments of the forum page of the mod. I plan to return to spacedock after it's resolved.

Just read your forum message, I believe that to be a firefox issue not a spacedock issue. Try using a different browser to access spacedock

**Comment by D4RKN3R** [comment]
> "central directory" most likely means there's something wrong with the ZIP file, but when I downloaded it and inspected it locally, the usual tools for validating ZIP files don't report any issues (otherwise I would have tried to contact you with a recommendation of how to fix it).

I use the default compression thing on my PC (Pop OS). The file extracts fine, and works fine after being extracted. Not sure what the issue with it would be.

**Comment by HebaruSan** [comment]
Well, the good news is that whatever that issue is, it might be specific to the upload that's currently on SpaceDock.
Or it might start happening again in the next release after this one. 🤷 

So switching the hosting over to GitHub should address both problems. I can do that in a couple of minutes...

**Comment by HebaruSan** [comment]
> Just read your forum message, I believe that to be a firefox issue not a spacedock issue. Try using a different browser to access spacedock

Alternately, a Firefox dev (!) apparently just posted a very jargon-heavy explanation of the issue that includes a workaround:

- <https://forum.kerbalspaceprogram.com/topic/170865-spacedockinfo-mod-hosting-site/?do=findComment&comment=4428045>
