### ISSUE TITLE
KAC not updated

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN#1114]
From forum:
```
John FX
So I'm having issues trying to install Kerbal Alarm Clock with CKAN. The version in CKAN says it is 3.2.3.0, the version released is 3.3.0.1. If I install it then it does not show in KSP. when I go to uninstall it then I get two lines in the changelog, one for 3.2.3.0 and another for 3.3.0.1. Removing works fine.

If I go to the download link in the KAC thread and manually install it works fine.

Not sure where the glitch might be but I thought I'd post the issue. 
```

We have ckan for new version (v3.3.0.1) here: https://github.com/KSP-CKAN/CKAN-meta/blob/72e2782a9c513f5004ee1e92587c026ce2c8cbad/KerbalAlarmClock/KerbalAlarmClock-v3.3.0.1.ckan but ksp_version is "1.0.0" so it not shows up for 1.0.2
On KerbalStuff it's marked as "KSP Version: 1.0" 

related discussion: https://github.com/KSP-CKAN/CKAN-meta/pull/431

We CAN do brutal hack and add "ksp_version": "1.0" to netkan file but you know... Not really elegant solution. I think we need to way to tweak ckan files and tell netkan to NOT override them.

**Comment by Dazpoet** [comment]
ugh, what a freaking pain... it seems we're indexing the version from the KAC .version file so the mod author needs to update that one to reflect compatibility with version 1.0.2.

The big question here is why the older releases have no ksp_version fields at all.

For now an ugly hack could work but if KAC has an active developer a post in their thread asking for an update to their version file might work?

**Comment by TeddyDD** [comment]
Why not ask on github @TriggerAu or create issue here? https://github.com/TriggerAu/KerbalAlarmClock/issues

**Comment by Dazpoet** [comment]
Well well what do you know :+1:

I constantly ask others to open github issues but I don't think to do so myself :p

**Comment by TeddyDD** [comment]
I should do it myself but I'm afraid my English still sucks :C

**Comment by Dazpoet** [comment]
Upon the closure of this issue it is very recommended to revert https://github.com/KSP-CKAN/CKAN-meta/pull/440 to maintain the authors versioning.

**Comment by TriggerAu** [comment]
KAC 3.3.1.0 shoudl have only Major and minor version in its .version file, so shoudl come across as 1.0

If not then let me know

**Comment by Dazpoet** [comment]
The bot has done a few rounds now and does not appear to register the update of KAC so I did some digging. For the `$vref` field to function the .version file must adhere to the [KSP-AVC spec](http://ksp.cybutek.net/kspavc/Documents/README.htm) which, from my understanding, requires a defined patchlevel.

A solution might be to set the KSP_VERSION_Min and KSP_VERSION_MAX fields aswell as the KSP_VERSION field. [CKAN spec](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#vref) indicates that as long as MIN and MAX fields are set the KSP_VERSION field will not be used so e.g. setting your .version to

```
    "KSP_VERSION":
    {
        "MAJOR"1,
        "MINOR":0,
        "PATCH":0
    },
    "KSP_VERSION_MIN":
    {
        "MAJOR":1,
        "MINOR":0,
        "PATCH":0
    },
    "KSP_VERSION_MAX":
    {
        "MAJOR":1,
        "MINOR":0,
        "PATCH":2
    }
```
will keep your 1.0.0 compatibility but will also extend it up to 1.0.2. Ofcourse this would generate additional work for your side when e.g. 1.0.3 comes out since the _MAX would have to be updated for consequent builds. I'm not sure how much work this is nor if it can somehow be automated so it is ofcourse up to you how you'd like to proceed.

**Comment by TriggerAu** [comment]
I'm pretty sure I got this right now. Let me know if its still not good

**Comment by Dazpoet** [comment]
Yep that did it! https://github.com/KSP-CKAN/CKAN-meta/commit/cd2548b8466e4570f81f43b058ecd21bfa3c98e2

Thanks for being so helpful @TriggerAu and I hope not to much of your userbase was negatively affected.
