### ISSUE TITLE
Some plugin not listed anymore but still updates.

### ISSUE THREAD

**Issue by Kitefr** [KSP-CKAN/NetKAN#1118]
Hey, 

I noticed some mods (UKS, Karbonite... for example) are not listed anymore when i update the list with the `ckan update` command in CLI.
When I do `ckan list`, i can see mods to update in my current mods list but, even if i can update then, i can see them in the `ckan available` list anymore.

Is this normal ?

I am using the version 1.6.12

**Comment by Dazpoet** [comment]
This is because users reported our Firespitter.dll didn't work in KSP 1.0 and as such I have removed that download from CKANs compatibility listing for 1.0. Since USI mods depend on that .dll they are no longer showing up.

Unfortunatly some users, like yourself, managed to grab USI mods prior to this change and as such you're currently stuck in limbo. I'm sorry this has happened to you and we're actively working on a solution.

**Comment by Kitefr** [comment]
No problem. I will just wait patiently !
Maybe remove some of the plugins... Make some tests. Thanks for answer !

**Comment by Dazpoet** [comment]
Firespitter.dll has been updated and is available again so this issue has played out it's part. Thanks for reporting it and have fun playing now that's everything is back to normal :D
