### ISSUE TITLE
Hooligan Labs Airships netkan file

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/NetKAN#1275]
I have done up a netkan file for Hooligan Labs Airships to save JewelShisen the effort. But now I can't figure out how to attach the file to this issue.

**Comment by mgsdk** [comment]
You can create a pull request and link/refer to this issue.

In case you've used git before, disregard the following:
I can see you've already forked the repository. You would then (ideally) create a new branch, add the file to that branch and then create a pull request back into this main repo. GitHub allows for online editing of files, see https://help.github.com/articles/creating-new-files/.

**Comment by politas** [comment]
Well, I've got the file in a branch, but how do I get it back to the KSP-CKAN/NetKAN repository, rather than my fork?

**Comment by politas** [comment]
Aha! That seemed more like it!

**Comment by mgsdk** [comment]
There may have to be a few revisions before our test-bot is happy with the result, but congratulations on generating your first PR (pull request) on GitHub :smile: (And making life easier for us at the same time).

You should be able to keep editing the file on GitHub, and any changes you make will automatically appear in the PR you have already created. Any comments on a specific PR will usually happen in the thread for the PR rather than the issue itself.

**Comment by politas** [comment]
With your suggested revisions, it has now passed the test-bot.

**Comment by politas** [comment]
Revised again as suggested. Is it all good, now?

**Comment by mgsdk** [comment]
Yes, it looks good now. I've merged it so it should show up soon. Thank you for your help, and I hope the process haven't discouraged you from doing something similar in the future.
