### ISSUE TITLE
KWRocketry forcing community fixes

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#2092]
The netkan for KWRocketry says it conflicts with the two Community Fixes, however when installing KWRocketry, it forces the CommunityFixes to be installed as well.

This is odd, since the community fixes depends on KWRocketry.

i would think that KWRocketry would suggest the two community fixes mods.

I originally created this, but someone on the NetKAN team rewrote it this way.

**Comment by plague006** [comment]
The netkan affects the official builds while KWRocketry-community is an independent .ckan file.

**Comment by linuxgurugamer** [comment]
I don't understand.  When I go into ckan.exe, and do a refresh, KW Rocketry shows up, author is Winston, and forces that the community fixes be installed.
When I look at the KWRocketry.netkan, it has both of the communityfixes listed as conflicts.

It appears that the KWRocketry-CommunityFixes.netkan is overriding the official KWRocketry.netkan, so that the KWRocketry official build can't be installed by itself.

**Comment by plague006** [comment]
Separate netkans and ckans -- .ckans/the CKAN-meta repo are what CKAN.exe use/care about. NetKANs are only used by bots to generate .ckans. So the KW .netkan is setup to take releases to the KW kerbalstuff page (official releases), we "snuck in" the KW-community release into the CKAN-meta repo as a higher version of the current KW release. The end effect is that until there's a new official KW release, KW community is the current version. The KW-community relationships have the community-fixes as dependencies, but once there's a new KW release (via the netkan), we don't want people to have both the new version of KW and the old community-fixes installed at the same time.

**Comment by plague006** [comment]
KW isn't compatible with 1.0.4 right? That's why we only allow KW-community to be installed (which require CommunityFixes).

**Comment by linuxgurugamer** [comment]
Understood.  However, when I filter on incompatible, the standard 1.0.2 version of KW doesn't even get listed.

**Comment by plague006** [comment]
Nor should it, unless you're running 1.0.2 (you can simulate this by changing the version in the readme.txt inside the main KSP folder). http://puu.sh/jymvO/f87cd8288a.png

**Comment by linuxgurugamer** [comment]
I disagree.  When I filter by incompatible, it shows me all the mods that
are for other versuons, including 0.90, 1.0.2, etc, except for kw

**Comment by plague006** [comment]
That's not accurate to how the incompatible filter functions. You do not see all the mods that are for other versions, you see mods that are not updated for your current KSP version. If you take an example like Module Manager: under the compatible filter you'll see the version as 2.6.7, but if you switch your filter to incompatible there are no listing for Module Manager. The behaviour you're describing is reminiscent of https://github.com/KSP-CKAN/CKAN/issues/1202.

In order to have KW listed as both a compatible and an incompatible mod, we would have to assign KW-community a unique identifier. This would have many negative side effects such as: difficulty in creating an upgrade path *to* KW-community, difficulty in creating an upgrade path *from* KW-community, confusion on why a mod is listed as both compatible and incompatible when, for 915 other mods, it's binary.

**Comment by linuxgurugamer** [comment]
Ummm, then I'm just seeing things.  Please see this link, which is a screen capture of a CKAN screen filtering by Incompatible:


You say that we don't see mods that are for other versions.  Isn't that the mostly the same as showing mods which are incompatible with the current version?

This is on a 1.0.4 game, CKAN v1.12.0-0
It clearly shows the Max KSP version, which is most definitely NOT 1.0.4 on all the listed mods.  So from what I'm seeing, these are mods which are for other versions

![ckan-screen](https://cloud.githubusercontent.com/assets/1630166/9223068/e7fc18b2-40c4-11e5-9483-ff74b92fdee0.gif)

I'm not trying to be argumentative, but what you are saying is not what is being shown.  Maybe I'm missing something, and maybe we should take this offline, since it apparently isn't a bug in your view.

**Comment by plague006** [comment]
If you're highlighting "0.35mm SSR..."; that's an incompatible mod with no compatible versions. And KW isn't listed as incompatible because it has a compatible version. I think I just wasn't clear, I'm saying a mod can't be both compatible and incompatible with the current filters.

**Comment by plague006** [comment]
Let me start from scratch, I think I should have better established the fundamentals. .netkans mean nothing to CKAN.exe, so focus on the .ckan files listed in the CKAN-meta repo. Inside CKAN-meta/KWRocketry exist `KWRocketry-2.7.ckan` which is the official release of KW for KSP 1.0.2. `KWRocketry-2.7.0-community.ckan` is actually just a copy of 2.7 with a different version number (2.7.0-community). The community release is tagged as compatible with KSP 1.0.4 and has dependencies on the community fixes to make that true. `KWRocketry-2.7.ckan` and `KWRocketry-2.7.0-community.ckan` have the same identifier `KWRocketry` and because they have the same identifier, as far as CKAN.exe is concerned they're different versions of the same mod.

Now that we have CKAN-meta, .ckans, and CKAN.exe out of the way.. We can talk about NetKAN a bit. NetKAN is simply a program that takes a .netkan file and inserts extra information from external sources. So for instance [ElectricCost.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ElectricCost.netkan) has as small a .netkan as you'll find. As far as information about the mod itself, all we have is an identifier, a license, and a $kref that points us to its KerbalStuff page. With that little $kref we know we can pull all the information about the mod that we need. You can see in [ElectricCost-1.0.0.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/ElectricCost/ElectricCost-1.0.0.ckan) all the information that is added. NetKAN creates .ckans, but doesn't know anything about other .ckan files or anything like that. NetKAN is "dumb" in that sense. So what that means for `KWRocketry.netkan` is that we can set a `conflicts` relationship with `KWRocketry-CommunityFixes` and it will only affect the current and future releases on the KerbalStuff page. So `KWRocketry-2.7.ckan` has the `conflicts` because NetKAN updated it, and the next release on the KerbalStuff page will also have the `conflicts`, but `KWRocketry-2.7.0-community.ckan` will never have the `conflicts` to `KWRocketry-CommunityFixes`.

Hope that was a better explanation. .netkan and .ckan usually are related, but `KWRocketry-2.7.0-community.ckan` is outside of that loop. .ckans are always the place to look for why CKAN is acting the way it is, .netkans can be used as a guide, but in complex situations like this (of an unofficial patch/fix) the .netkan is way more confusing than helpful.

**Comment by linuxgurugamer** [comment]
Yes, it is, thank you.

I appreciate your patience.
