### ISSUE TITLE
Nexus Mod not updating

### ISSUE THREAD

**Issue by TiktaalikDreaming** [KSP-CKAN/NetKAN#2275]
Hi.
I'm the author of the mod referenced in  NetKAN/NetKAN/SuperHeavyBoostersHistoricalNexus.netkan

I can't get CKAN to update it's idea of what version this should be and I'm lost with why it won't.  The NetKAN file was (by the look of it) autocreated when the mod was at v0.9, which was a bad starting place regarding folder structure in the archive, but the NetKAN file just seems to say it wants a "Nexus" folder, which is right.

Any ideas?

**Comment by techman83** [comment]
Yep. I've submitted a PR that'll sort this out. Someone will merge that and it'll get picked up by the indexer on the next run. You can check it's status here -> http://status.ksp-ckan.org/

**Comment by plague006** [comment]
The creation of netkan file was not automated or done by a  bot. It was created by @mgsdk. The indexing of the mod began at 0.9 because that's when we were made aware of your mod's existence. We don't retroactively index old versions of mods because we don't have the required information to generate the metadata.
