### ISSUE TITLE
RSS Expanded releases 2 updates at every new release

### ISSUE THREAD

**Issue by Olympic1** [KSP-CKAN/NetKAN#2843]
[RSS Expanded](https://kerbalstuff.com/mod/1008) has updated to 1.0.5, and the latest kopernicus, but at every release @pozine releases 2 "versions" on KerbalStuff. One release with normal textures called `Version 0.12.0` and then another release with reduced texture size called `Version 0.12.0_LITE`.

Making a `.netkan` file for only the configs is possible, but could it be possible to use `asset_match` (or something else) to find both releases so users can choose to install the normal or lite version?

**Comment by Olympic1** [comment]
[RSS Expanded](https://kerbalstuff.com/mod/1008) has updated to 1.0.5, and the latest kopernicus, but at every release @pozine releases 2 "versions" on KerbalStuff. One release with normal textures called `Version 0.12.0` and then another release with reduced texture size called `Version 0.12.0_LITE`.

Making a `.netkan` file for only the configs is possible, but could it be possible to use `asset_match` (or something else) to find both releases so users can choose to install the normal or lite version?

**Comment by plague006** [comment]
Tagging @pjf and @dbent because I think they're most likely to have an answer to this.

**Comment by politas** [comment]
There are times when CKAN's inability to select older versions of a mod can be a pain.

**Comment by dbent** [comment]
There's no mechanism for that right now.

It could be written with one caveat: Right now we select the latest version of a KerbalStuff mod by using the `default_version_id` provided by KS. In order for something like this to work we would have to have a regex for the version string and then iterate through the list of available versions and select the "latest" one that matches the provided regex. Right now versions are provided as an array, but there's nothing in the KS metadata that particularly guarantees in what order versions will be returned. It appears versions are returned newest to oldest but that may be subject to change in the future, in which case we'll have a *really subtle* break where NetKAN will fail to pick up new releases of certain mods. I wouldn't want to add such a feature unless @SirCmpwn says the ordering of `versions` is stable and part of the API.

In any case I'd be curious if there's a particular reason that the mod is released like that. Other mods with such variants typically just have multiple mods on KS. From a user's perspective that would seem more convenient since if I'm only interested in the "Lite" variant, I don't have to constantly go to the changelog of the mod to get the variant I want and can just click on the big fat download button on the lite variant's landing page.

**Comment by Olympic1** [comment]
idk how I closed and reopened the issue.

Pinging @pozine as he can explain if there is a particular reason after that.

**Comment by politas** [comment]
Could be related to me fixing the typo in the subject?

**Comment by plague006** [comment]
From what I understand, there's nothing more to be done here. SpaceDock sends a webhook so we now index every spacedock release but to do the same for GitHub each individual mod author would have to set up their own webhook to trigger the indexer.

I imagine there would also be security and logistical concerns trying to set that up.

I'm closing this but feel free to re-open if I misunderstand the webhook/indexer process.
