### ISSUE TITLE
Can't install [1.1] 'Project Orion' Nuclear Pulse Engine using CKAN. Error USI Core missing

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3511]
Can't install [1.1] 'Project Orion' Nuclear Pulse Engine using CKAN without getting a popup

Error: Module USI-Core has not been found. This may be because it is not compatible with the currently installed version of KSP

Last tested on CKAN 1.16.1 for KSP version

build id = 01174
2016.03.31 at 00:58:13 CEST
Branch: prerelease

Readme.txt Version 1.1.0 Pre-release

Roverdude wanted to take at look at this first. Reporting back :_ The current versions of these mods are all for KSP 1.1, not KSP 1.0.5 - I've confirmed the KSP-AVC version files, so this is going to be a CKAN issue._

I suspect the max ksp version should be set to 1.0.5 for previous versions and the latest update set to min Ksp 1.1.0

**Comment by dbent** [comment]
That's because `USI-Core` has a dependency on `FirespitterCore` which has no KSP 1.1.0 compatible version available (at least in CKAN). Since it appears @BobPalmer has been doing [releases](https://github.com/snjo/Firespitter/releases) of Firespitter, it'd be up to him.

On a related note, the fact that that dependency availability isn't transitive is annoying (if `USI-Core` is marked unavailable because of one of its dependencies isn't available then `USI-NuclearRockets` should be marked unavailable as well). I'll create an issue for that.

**Comment by dbent** [comment]
Created an enhancement issue to better handle this kind of case: KSP-CKAN/CKAN#1646

**Comment by nobodyhasthis** [comment]
@dbent. i can't say why the fire spitter release page you liked to has not been updated. However it was been updated to 1.1 on https://github.com/snjo/Firespitter/tree/master/For%20release

As always I honestly don't know if this helps us or if I need to back to the author?

**Comment by dbent** [comment]
It has to be published on the releases page, that's where CKAN picks it up from. @BobPalmer (RoverDude) has already been pinged, it's up to him what he wants to do.

**Comment by nobodyhasthis** [comment]
Ok situation has improved. Dependency for USI core should be fix I hope. Firespitter updated for 1.1. Release page updated now https://github.com/snjo/Firespitter/releases

I hope we can use this to get [1.1] 'Project Orion' Nuclear Pulse Engine back on line.

**Comment by dbent** [comment]
It should be installable now.
