### ISSUE TITLE
Redirect GoodSpeed to GPOSpeedFuelPump

### ISSUE THREAD

**Issue by henrybauer** [KSP-CKAN/NetKAN#3770]
So, I screwed up when taking over this mod, and clicked "add to CKAN" when adding it to SpaceDock.  Now there's two entries:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Goodspeed.netkan
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/GPOSpeedFuelPump.netkan

Is there any way to redirect people trying to install "Goodspeed" to instead install "GPOSpeedFuelPump"?

**Comment by plague006** [comment]
I added it under a separate identifier because the github page explicitly states it's a fork and the KSP forum thread is different from the original and includes the word `continued`.

With that said `Goodspeed` isn't available for ksp 1.1 and `GPOSpeedFuelPump` isn't available before ksp 1.1 so there's no overlap and therefore no need to redirect anything. If you'd like though we can hardcode the `name` as `Goodspeed` if you'd like. (The identifiers `Goodspeed` and `GPOSpeedFuelPump` aren't user-visible and can't be changed but the `name` that users see in the CKAN client can be changed).

**Comment by henrybauer** [comment]
Yep, your actions were reasonable given the information at hand; I didn't mean to imply that you did something wrong.

I just figured a redirect would help anyone with the old one installed to automatically upgrade, but I guess most people just started fresh for 1.1 anyways.  If it's not possible to do some sort of redirect then such is life :)
