### ISSUE TITLE
Some 1.1.2 compatible mods missing from CKAN

### ISSUE THREAD

**Issue by yump** [KSP-CKAN/NetKAN#3855]
[Ferram Aerospace Research](https://github.com/ferram4/Ferram-Aerospace-Research/releases)

[Kerbal Flight Indicators](https://github.com/DaMichel/KerbalFlightIndicators/releases)

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/CKAN-meta/blob/master/FerramAerospaceResearch/FerramAerospaceResearch-3-0.15.6.3.ckan was added a day ago - if it's not listed it's because it's waiting on an update to ModularFlightIntegrator

https://github.com/KSP-CKAN/CKAN-meta/blob/master/KerbalFlightIndicators/KerbalFlightIndicators-R11.ckan modified 2 hours ago

Thanks for the heads up, it's appreciated.
