### ISSUE TITLE
Changing mod's identifier: surfacelights => SurfaceLights

### ISSUE THREAD

**Issue by ihsoft** [KSP-CKAN/NetKAN#4139]
Hello,

I'm a maintainer of SurafceLights mod which is used to be addressed by https://github.com/KSP-CKAN/CKAN-meta/blob/add349f09f0cd04908545641ba8f63fa5843431e/surfacelights/surfacelights-1.2.3.ckan meta record. Now, with migration to NetKAN the related record indicates the mod is frozen (surfacelights.frozen). I was going to drop the frozen file and create .netkan file instead but then noticed that settings are not quite right. Specifically, the identifier is spelled as "surfacelights" instead of more user friendly "SurfaceLights". Doing such a change in the new .netkan file results in conflicts in ckan when trying to install the mod. It looks it does checking case-sensitive:
```
Installing mod "SurfaceLights 1.2.4.0"
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/SurfaceLights/LICENSE.md
Installing Mod : SurfaceLights 1.2.4.0
Owning Mod     : surfacelights
CKAN Version   : v1.16.1-0-g2e91715 (beta)

Your GameData has been returned to its original state.
```

So, the question. What is the right approach in such a case? It looks there was a conflict in the past with the mods but now the conflicting mod is deprecated.

**Comment by plague006** [comment]
The correct approach is to leave the `identifier` as is while updating `surfacelights.frozen` to `surfacelights.netkan`.

----

Changing `identifiers` is an ugly prospect. Someone who currently has `surfacelights-1.2.3` installed will not be able to install `SurfaceLights` (as you found out) because it tries to install files that `surfacelights` already installed. Additionally we currently have to way for users to upgrade seemlessly from mod `X to mod `Y`. They would have to uninstall `surfacelights` and install `SurfaceLights` (and we currently have no method to indicate that something like that needs to be done`. Because there's no upgrade path you would have a split userbase with some perpetually on `1.2.3`.

>the identifier is spelled as "surfacelights" instead of more user friendly "SurfaceLights"

Users don't typically see the `identifier`, they see the `name` of a mod. While I agree the capitalization is sub-optimal, it's not something readily apparent to end users.

**Comment by ihsoft** [comment]
User actually do see the identifier: in the right-bottom window in the client. Though, given how problematic the change is I think it's not worth it.
