### ISSUE TITLE
Cache clearing

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#4185]
@techman83 a number of mods are failing to index. I'm not sure how long they've been stuck, but the screenshots indicate it's been more than 1 bot run.

http://puu.sh/pe5Nx/19db0ced44.png

http://puu.sh/pe7z8/4df8d57da1.png

**Comment by Cphoenix** [comment]
[Related forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1161-13-mar-2016/&do=findComment&comment=2612638).

**Comment by plague006** [comment]
> Perhaps the authors changed the folder structure in their downloads or something.

Looked into that, they all run fine locally.

**Comment by Cphoenix** [comment]
> Looked into that, they all run fine locally.

Nuts. Clearly something wrong with the bot. 😕

**Comment by techman83** [comment]
@plague006 fixed. I'd added an enhancement to the bot to have a configurable cache path instead of mucking around with Symlinks. In the process I configured it to a logical place, which meant the cronjob taking care of dud downloads was looking in the wrong spot. Resolved and all those inflated correctly now.

I should go look at NetKANs code and fix that little annoyance properly.
