### ISSUE TITLE
ContractConfigurator-KerbalAcademy "homepage" error message

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#4203]
There is still broken homepage link showing up within ContractConfigurator-KerbalAcademy
"homepage" : "http://forum.kerbalspaceprogram.com/index.php?/topic/140739-"
leading to blank page with error message.

Originally this was going to be 
"homepage" : "http://forum.kerbalspaceprogram.com/index.php?/topic/140739-1"
Which was does not seem to be correct. See #4174 & #4175 

So I was wondering if the full address should have be used which is this
"homepage" : "http://forum.kerbalspaceprogram.com/index.php?/topic/140739-112-contract-pack-kerbal-academy"

Sorry if that is a silly question. I am just trying to learn more and hopefully help out a nice mod author as well. All feedback welcome.

**Comment by plague006** [comment]
Indeed #4175 did not fix what it purported to, https://github.com/KSP-CKAN/NetKAN/commit/f34cc3febf2cd63637d57ba76de1fe64e8af8d55 does.

All that was required to make the link work was adding a character (any character) after the hyphen. I chose to use the thread's title since I like descriptive links.
