### ISSUE TITLE
Splitting RO craft files out of RO

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#4498]
https://github.com/KSP-RO/RealismOverhaul/pull/1332 involves splitting our craft files out into a new package which the core RO package then recommends.

Does this look sane to you? If so, what netkan-side changes need be made? Making a new netkan stub to point to our new netkan? What else?

**Comment by politas** [comment]
If you make the craft package a min_version of the RO dependency I assume you are giving it, it might remove the need for users to uninstall and reinstall.

**Comment by NathanKell** [comment]
Sorry, can you, uh, "refresh my memory"* on what you mean by setting it as a min_version of the dependency?

*Well, to be fair I think I did know what that meant once, it's just totally gone now.

**Comment by politas** [comment]
Never mind. I don't think I can remember what I was thinking. The issue is that people trying to install the craft files mod will have an issue if they are still included in their RO mod installation, meaning they will need to uninstall RO first, then install both separately. If you made the crafts mod _not_ a dependency, then RO could update, removing the craft files in the process, and _then_ users could install the craft files mod.

How much of a requirement are the craft files?

**Comment by NathanKell** [comment]
I think we can safely put them as a rec rather than a dep. @raidernick ?

**Comment by politas** [comment]
I think you are, actually.

**Comment by NathanKell** [comment]
Then it shouldn't be a problem, right?

**Comment by politas** [comment]
Might be worth priming your CKAN users to do the update of RO first, then install the craft files separately.

**Comment by NathanKell** [comment]
Good point.

**Comment by raidernick** [comment]
@politas all of the craft files names were changed anyway just for this exact situation. Even if it were a required dependency, since the names are changed it can't conflict. Worst case users would end up with the old copies and the new renamed ones.

**Comment by politas** [comment]
Ah, no worries at all then! Just need the new meta-netkan for the craft mod.

**Comment by politas** [comment]
So, with the results we've gotten in #4581, it seems clear that at least some users are going to have to uninstall and reinstall RO in order to install the new RO-Crafts mod.
