### ISSUE TITLE
conflict with texture replacer and Pood's Calm Nebula Skybox

### ISSUE THREAD

**Issue by T33J** [KSP-CKAN/NetKAN#4767]
About to install...
- Pood's Calm Nebula Skybox 1.0.0(cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/TextureReplacer/EnvMap/NegativeX.png
Installing Mod : PoodsCalmNebulaSkybox 1.0.0
Owning Mod     : TextureReplacer
CKAN Version   : v1.20.1-0-gd41fe54 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Lachdenan** [comment]
I'm glad you brought this up. I was going to do this myself.

**Comment by Bit-Fiddler** [comment]
This is true for all the Pood sky boxes...

**Comment by Poodmund** [comment]
I think it's because RangeMachine, who is maintaining TextureReplacer, may have accidentally included the following files in the latest distribution, v2.5.1.

- GameData\TextureReplacer\EnvMap\NegativeX.png
- GameData\TextureReplacer\EnvMap\NegativeY.png
- GameData\TextureReplacer\EnvMap\NegativeZ.png
- GameData\TextureReplacer\EnvMap\PositiveX.png
- GameData\TextureReplacer\EnvMap\PositiveY.png
- GameData\TextureReplacer\EnvMap\PositiveZ.png

If these files are removed from the TextureReplacer distribution, the installation of any/all Skyboxes via CKAN will not be an issue as TextureReplacer will not have any files in the EnvMap folder by default.

**Comment by Olympic1** [comment]
On it

**Comment by Olympic1** [comment]
Made #4780 to fix this for future versions.

**Comment by Poodmund** [comment]
Please be aware @Olympic1 that RangeMachine is removing these files from his future releases of TR: https://github.com/RangeMachine/TextureReplacer/issues/1#issuecomment-254634616

**Comment by Olympic1** [comment]
Thx for the update

**Comment by Dazpoet** [comment]
Is this resolved and ready to be closed?
