### ISSUE TITLE
Environment visual enhencement not compatible with 1.2.2 in CKAN

### ISSUE THREAD

**Issue by mike855** [KSP-CKAN/NetKAN#5030]
Environment visual enhencement is not compatible with 1.2.2 in CKAN, can you add it in compatibility list?
It cause problems with some depedencies

**Comment by Dazpoet** [comment]
It doesn't work due to the [ksp_version_max restriction](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/EnvironmentalVisualEnhancements.netkan#L9) requested by the [author](https://github.com/KSP-CKAN/NetKAN/issues/4946) so I guess we'll ping @WazWaz for confirmation on how to resolve the issue. Is a new version of EVE on its way or should we bump it up another notch?

**Comment by mike855** [comment]
As see in the forum the actual version works : http://forum.kerbalspaceprogram.com/index.php?/topic/149733-121-environmentalvisualenhancements-12-2/&page=8

**Comment by Dazpoet** [comment]
Perfect, that's all I need. See the above PR
