### ISSUE TITLE
How to retire a mod?

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5138]
I need to retire the mod I have for Zero Point Inline Fairings for Stock, it's a patch for ZPf, which doesn't seem to be available on CKAN anymore

How do I do this?

Thanks

**Comment by Dazpoet** [comment]
By retire do you mean you will remove all former downloadlocations as well? If so you'd probably want to purge the CKAN-meta folder for the mod-listing since they'll all 404.

If by retire you just mean no more development but all former downloadlocations will stay in place and no further releases will be made, you can just leave it be since the NetKAN indexer just won't do anything with it. Should you want to lessen the load on the indexer you can change the file extension of the netkan in question from .netkan to .frozen and the indexer won't touch it anymore.

**Comment by techman83** [comment]
@Dazpoet If it's an opensource mod the files will be on the Internet Archive. I believe @dbent has some ideas around an implementation.

**Comment by Ruedii** [comment]
If you have the mod's source on Github, you should leave it up for posterity's sake.  You never know when it will come in handy.

As of retiring it from being indicated for future KSP versions, just mark it as not compatable with versions over a certain release.

Yes, zero point inline fairings were recently integrated into stock.  Specifically, you can now turn off the truss structure for your inter-stage nodes, allowing this feature among others.  You still need to attach some form of decoupler to the node, but that isn't an issue.
