### ISSUE TITLE
Guidance needed for merges

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5251]
@KSP-CKAN/wranglers

I'm looking for some guidance regarding merges.  and I have no easy way to contact all of you other than this (if there is a mailing list, please let me know)

I often see a  number of PRs waiting to be merged, and usually leave them (especially my own) for others to merge.  This unfortunately results in delays of days and sometimes weeks before a new mod is merged.

Usually the only ones I merge are those which I check to see that there aren't any unexpected requirements, etc.

Can someone please contact me and let me know what to do?  I'd like to clean up the backlog a bit.
Thanks

**Comment by Dazpoet** [comment]
Back in the day when it was basically me doing all of the metadata-wrangling I had no issues merging my own PRs since it's not like we'll break the client or anything. Metadata changes are, imo, safer than going on mergesprees in say the KSP-CKAN repository. There are obviously some PRs which require discussion, examples of mine being e.g. #889 #939 and #1568 but those are oftentimes easy to recognize.

I see you poking around on irc and I think it'd be a better idea to throw out questions rather than asking if anyone is around. Part of the allure of irc, to me atleast, is being able to answer a question when I have the time rather than hoping to be around in the same time as someone else.

**Comment by politas** [comment]
Yeah, asking a question on IRC is better than just asking if anyone is around. The Qboid bot lets you leave a message that triggers when someone posts, so we can answer you that way (though I've forgotten the syntax)
