### ISSUE TITLE
RSS Constellations: File collision

### ISSUE THREAD

**Issue by moira-lachesis** [KSP-CKAN/NetKAN#5292]
File           : GameData/RealSolarSystem/RSSKopernicus/Sun.cfg
Installing Mod : RSSExtrasolar 1.0
Owning Mod     : RealSolarSystem
CKAN Version   : v1.22.1-0-g174271a (beta)

Real Solar System 11.4.0 is installed.
RSS Extrasolar 1.0 won't install because it is trying to overwrite this file.

Is there a workaround?

**Comment by politas** [comment]
The only workaround I can think is to manually delete the Sun.cfg file before installing RSS Extrasolar, but you'll have to mess with it every time you upgrade, unfortunately. Is the RSSExtrasolar version of the file substantially different to the RealSolarSystem version? If it's the same, we could filter that file out, since RealSolarSystem is a dependency for RSSExtrasolar.

**Comment by politas** [comment]
What version of KSP are you running? Given that RSSExtrasolar 1.0 is for KSP 1.1.3, I don't think you'll have any worries about upgrades until you move to KSP 1.2.2, for which the whole RSS/Extrasolar installation is different.
