### ISSUE TITLE
EVE update and filename change (to something sensible)

### ISSUE THREAD

**Issue by WazWaz** [KSP-CKAN/NetKAN#5427]
I've posted a new update (mostly bug fixes) for EVE. I've changed the filenames to a meaningful one too.

Is there a way for NetKAN to automatically get new non-beta releases from github?

https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases

**Comment by politas** [comment]
It'll happily get new versions automatically if the filenames don't change. I'll have to put in a change for the new filenames.

Also, we are currently hard-coding the KSP version info, since there's nowhere we can scrape it from. If you were to include a KSP-AVC ".version" file, we could get those changes automatically, too.

**Comment by WazWaz** [comment]
Hmm, so encoding the version number into the filename was a bad idea? It really is best for non-CKAN users (for whatever that's worth) to have them.

EVE doesn't use KSP-AVC (I really don't see the point of AVC - CKAN handles versioning holistically, not on a per-mod basis), does that matter?

I'm eager to make whatever changes to the packaging that makes everyone's life simplest.

**Comment by politas** [comment]
No, the version number is fine, we match on the portion of the zip filename up to that. I think everything is working fine now. Just keeping a consistent naming and version numbering system is what'll make us happy!
