### ISSUE TITLE
Wernher's Old Bits will not install

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#5625]
This mod reports the download file is corrupt.

**Comment by benjwgarner** [comment]
The download that is available now for the newest version when this issue was opened (0.16) matches its hashes in its [CKAN-meta file](https://github.com/KSP-CKAN/CKAN-meta/blob/master/WernhersOldBits/WernhersOldBits-0.16.ckan). Since the .ckan file was [never changed](https://github.com/KSP-CKAN/CKAN-meta/commits/master/WernhersOldBits/WernhersOldBits-0.16.ckan) after it was created, it appears that only the copy you downloaded was corrupt. Clear your CKAN cache (`Settings => CKAN settings => Clear cache`)and try it again. If you can give more information about what version of WehrnersOldBits you were downloading when this happened, we can confirm that this is what happened (I'm just assuming you were downloading 0.16). Note that the current version, 0.16b, is different.
