### ISSUE TITLE
SUPPORT: How does Netkan update a mod?

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#5994]
Hi, Sorry to raise this as an issue, but I figure this is possibly the best place?

So I've taken over the KDEX mod and added it to Netkan (many thanks for various assistances rendered so far!).  However, since re-releasing the original I've made several small patch releases, however Netkan does not appear to be picking them up, and hence they don't show up in CKAN either.

The v1.10 release -did- end up in CKAN, however that was after I asked a question on IRC so not sure if somebody poked something manually (unfortunately I wasn't able to hang around until someone was able to answer).

My impression was that every time I make a new release on GitHub, Netkan picks it up (after some time), generates the new ckan metadata, and updates the repository. However, according to the [netkan bot run](http://status.ksp-ckan.org/) it was last checked 6 days ago, but there's been a point-release made 8 days ago.

So either I'm just being too impatient, or perhaps I've simply misunderstood how it's all supposed to work.

So my actual question is: what do I have to do to get an updated version of a mod, released on GitHub, into CKAN, preferably automagically?

Thanks.

**Comment by politas** [comment]
Yeah, the netkan-bot seems to be stuffed. I'll chase @techman83.

**Comment by HebaruSan** [comment]
I believe this is reporting the same problem as #5992 (the bot is not running), which I have updated to remove the ambiguity now that we have a report of a mod not updating (I previously was not sure whether the problem was with the bot running or just updating the status page). I'm going to close this issue to keep things tidy; please direct all further updates on this problem (or any other mod not updating) to that issue.

@politas, would it be OK if I made a public announcement about this on the forum thread? This could be causing confusion for many users and modders with the usual attendant forum traffic, and it would be nice to communicate the status since we know there's an issue.
