### ISSUE TITLE
Galactic Neighborhood and Planet Packs in general

### ISSUE THREAD

**Issue by Sigma88** [KSP-CKAN/NetKAN#6078]
First of all I apologize for the wall of text, it came out longer than I expected 😐

my mod "GN" requires planet packs to be installed in a specific way in order to funcion properly, and with the addition of more and more planet packs, I think CKAN could be a very useful tool to help players install these mods correctly.

since the installation of these planet packs might differ slightly from the one setup on CKAN, I would like to create a set of .netkan files that handles installation of GN and planet packs for GN

I am willing to maintain those files myself, unless some of you preferes handling the files themselves

I would like to get some feedback from you about some points:

### • Hiding mods

is it possible to hide mods from CKAN unless certain conditions are met?

eg: on a clean install, CKAN shows all planet packs available + GN, but hides all GN-specific packs

if the user selects any planet pack, GN becomes invisible.

if the user selects GN, all planet packs become invisible and the GN-specific packs become visible

### • KSP version compatibility

most planet packs compatible with GN have been long abandoned and are not officially compatible with the latest KSP version.

in most cases that's just a matter of form, meaning that the mod is actually compatible but hasn't been officially declared so by the dev (who has abandoned it)

in other cases the mod is actually not compatible, but within GN I provide patches that fix all compatibility issues basically making the mod compatible as long as it's installed with GN

I usually do this only for abandoned mods, mods in active development (like RSS) are still dependent on their developers to fix compatibility so that I don't risk developers getting bug reports from GN mods

I would like to add the GN-versions of these (abandoned) mods as they were compatible with the KSP version GN uses, but I'm not sure what your policy is about that

### • "provides" : [ "PlanetPack" ]

at a certain point, all planet packs were providing the tag "PlanetPack"

that would come in handy with GN but I noticed that this is not used anymore, is there an easy way to make GN not compatible with all planet packs by default, without having to edit all planet pack's netkan files?

maybe I could make GN incompatible with Kopernicus, and provide a GN-specific version of Kopernicus

this would allow to make sure GN is only installed with the mods that are compatible with it

**Comment by HebaruSan** [comment]
A few responses. I expect I've misinterpreted some things, so consider this just a continuation of the dialog.

### Hiding mods

As far as I know, the only thing that can cause a mod to be hidden is if it doesn't match the currently selected filter; the default filter is "Compatible", which shows mods that are compatible with the currently installed version of KSP, but there are also other filters such as "Cached" or even "Incompatible". Hiding probably isn't desirable, though---think about exceptional cases where the user corrupts their install by deleting random files, etc., we would just make it that much harder to clean up if mods could be in an invisible state.

I would advise to plan the approach to GN around the assumption that all of the mods involved will always be visible.

### GN-incompatible planet packs

I would think GN would be marked as conflicting with these mods, in GN's metadata, since GN is the one with special requirements.

### GN-compatible planet packs

If these are abandoned, and especially if they do not work in 1.3.x without GN's patches, we could mark them as depending on GN. Maybe give them a "GN-" prefix to make it clear that they're essentially content packs for GN.

If a planet pack can be used either with or without GN, then we could just leave it as-is, with neither a conflict nor a dependency.

### Policy on indexing abandoned mods without authors' consent

Frankly I am confused about what the official policy is at this point. I make a habit of asking authors before I index anything and refraining from merges without permission, and other team members seem to be doing the same, but the response to KSP-CKAN/CKAN#2147 makes it look like that is personal courtesy rather than policy. @politas?

One option, depending on licensing, might be for you to formally adopt these mods as their new maintainer. Then we would have the (new) author's permission. @linuxgurugamer does this two or three times per day and could probably share some advice on how to go about it.

### "provides": [ "PlanetPack" ]

I don't think this would help you. If this was a convention, then it should be followed by both the mods that are compatible with GN and the ones that are incompatible, otherwise you would have to explain to authors or users how some planet packs are not actually planet packs.

### Another Kopernicus

Please no. Why can't GN itself be the central mod in the relationship spiderweb?

**Comment by Sigma88** [comment]
the problem is that new planet packs pop up like mushrooms these days

I don't have the time to keep GN's metadata up-to-date with all new planet packs that come out.

plus all mods that require Kopernicus will be automatically incompatible with GN, because GN requires the install to follow specific instructions and can't work properly if stuff not marked expressively as compatible is added.

after giving it some thought I came to the conclusion that the best way to approach this is to have a completely separated "ecosystem" possibly using a different kopernicus so that I can easily mark everything as conflicting by adding GN as conflicting with kopernicus/scatterer/EVE

the downside is that the player will have to re-download the kopernicus archive as if it was a different mod, but honestly the size of the download is so small that I hardly think that it will be an issue


that said, if this is agains the spirit of CKAN I completely understand and I won't complain

**Comment by HebaruSan** [comment]
What about planet packs that can be used with or without GN (so far I understand that there are some such mods)? Those would depend on Kopernicus, so you would lose the ability to install them alongside GN.

**Comment by Sigma88** [comment]
yeah I realized that as soon as I sent my message

is CKAN smart enough to not download twice the same archive even if it's listed in two different "mods"?

**Comment by HebaruSan** [comment]
Yeah, if the URL is the same, it will be downloaded once, saved to the cache, and then re-used as needed.

**Comment by Sigma88** [comment]
ok, if this is the case then I think the best way would be to create alternate versions of those mods that are defined specifically for GN

most mods will require a different installation than the one already on CKAN  anyways since most planet packs provide clouds for EVE and other things that are not compatible with GN, so either you will need to split the installation of those mods in multiple parts (with the risk of breaking the installation of the original mod, which I think would be a bad idea)

or we use a different metadata to install the mod like I am already doing with SASS

@Olympic1  @politas  any suggestions?

**Comment by Sigma88** [comment]
here's a proof of concept of what I would like to do:

https://github.com/Sigma88/CKAN/tree/master/GalacticNeighborhood

**Comment by politas** [comment]
> Frankly I am confused about what the official policy is at this point. I make a habit of asking authors before I index anything and refraining from merges without permission, and other team members seem to be doing the same, but the response to KSP-CKAN/CKAN#2147 makes it look like that is personal courtesy rather than policy. @politas?

Restricted-licence mods require author approval before listing. That is not a legal requirement, as CKAN is not strictly redistributing anything, it's a community standard we have adopted.

For freely-distributable mods, the policy is that we make a good faith attempt to contact the author so that they can choose to opt-out from listing on CKAN before we list their mod. We should allow the author at least a week to respond before listing the mod under the implied permission of the freely distributable licence.

Obviously, for mods that have come in via Space-Duck, we have an affirmative statement from the author that they wish the mod to be listed (or at least, the person who put it up on Spacedock)

Does that make it clear?

**Comment by Sigma88** [comment]
I decided to make an installer for gn planet packs since the installation of those packs is different from the standard installation so there is no need to mess everything up in the ckan files.

Closing this issue
