### ISSUE TITLE
Infernal Robotics Legacy Parts has Max KSP version set to 1.1

### ISSUE THREAD

**Issue by moggers87** [KSP-CKAN/NetKAN#6131]
Background
----------

**CKAN Version:** 

v1.22.6

**KSP Version:** 

1.3.1.1891

**Operating System:** 

Linux

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
 
N/A

**Affected mods and mod versions:**

Infernal Robotics and Infernal Robotics Legacy Parts

Problem
-------

**What steps did you take in CKAN?**

1. Installed Infernal Robotics
2. Saw that no parts were available
3. Found an issue on this repo that said I needed to install legacy parts

**What did you expect to happen?**

That "Magic Smoke Industries Infernal Robotics - Legacy Parts" would show up in a search of compatible mods.

**What happened instead?**

The legacy parts mod shows up as requiring KSP 1.1, while the main mod is listed as compatible with 1.3. Setting CKAN's compatible versions to include 1.1 allowed me to install the legacy parts, with everything working as far as I tested (a few hinges and rotators in a single group, on the launchpad and in the VAB)

Looking at the metadata files, it appears that [InfernalRobotics.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/InfernalRobotics.netkan) doesn't specify a KSP version, but [InfernalRobotics-LegacyParts.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/InfernalRobotics-LegacyParts.netkan) does.

I don't know enough about KSP internals, but I would have thought that parts-only mods work on any version of KSP (I can see a few parts-only mods that are listed as "All Versions"). Alternatively, the legacy parts mod could require version 2.0.x of Infernal Robotics if compatibility with future versions of IR is a concern.

**Comment by HebaruSan** [comment]
Thanks for bringing this to our attention!

CKAN is telling the truth about the parts pack - [it hasn't been released since KSP 1.1.3](https://github.com/MagicSmokeIndustries/InfernalRobotics/releases). IR 2.0.14 includes only the Core package, presumably on the assumption that users will manually install an older parts pack. The most recent version of the Full package is 2.0.5, which was for KSP 1.1.3, explicitly labeled as such in its KSP-AVC file. (CKAN hasn't indexed that version because the download file name was switched from IR-LegacyParts.zip to IR-2.0.5-Final-Full.zip.)

That leaves CKAN with two bad options:

1. Mark the 2.0.0 version of the parts as compatible with any KSP version, even though 2.0.5 is available. Potential bad impact on mod authors if there were fixes to the parts in 2.0.1 through 2.0.5, which CKAN users would then not see and possibly file duplicate reports for on the forum thread.
2. Use the 2.0.5 Full download, extract just the Parts folder from it, and ignore its version file.

Ideally we would do neither; it's a bad idea to mix and match pieces of different versions of a mod, even if it seems to work with the versions that are available today.

We should be using the latest available version _with_ accurate version info. To do that, the mod authors would need to create a release of the parts pack that says it's compatible with KSP 1.3.1 (or if they prefer, all versions).

Do you happen to know why the authors stopped releasing the parts?

**Comment by HebaruSan** [comment]
I guess a third option would be to de-list the core InfernalRobotics package until the parts situation gets straightened out. At least that would reduce confusion among CKAN users, who appear to be the primary ones affected by these packaging problems. It could be done by making InfernalRobotics depend on InfernalRobotics-LegacyParts; that way they'd both reappear together once the parts pack is fixed.

**Comment by HebaruSan** [comment]
Found only one mod for KSP 1.3.x that depends on InfernalRobotics:

https://forum.kerbalspaceprogram.com/index.php?/topic/97146-130-mobile-frame-system-mfs-v033-29052017/

And even that one says:

> Known issues:
> - Parts that use infernal robotics are currently broken.

So if IR disappeared from CKAN temporarily, it shouldn't break any installs that aren't already broken.

**Comment by moggers87** [comment]
> Do you happen to know why the authors stopped releasing the parts?

No idea, sorry.

Thanks for the quick response btw ☺

**Comment by HebaruSan** [comment]
On further consideration, I concluded that option #2 is the best choice. The parts files had not changed at all between 2.0.0 and 2.0.5, which is strong support for the idea that they are compatible with all game versions, but we should be using the latest file name convention just in case there is a need to update them. CKAN users should be able to get a working IR install now.
