### ISSUE TITLE
NearFutureProps

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6217]
CKAN has **Near Future IVA Props** v0.7.5 which put files to **NearFutureProps** folder with **NearFutureProps.version** 0.2.1.

KSP AVC tells what there is new 0.3.0 version of **NearFutureProps**.

**StationPartsExpansionRedux** need >=0.3.0, 
**StationPartsExpansion** maybe works with 0.2.1 maybe 0.3.0, maybe both.

**Comment by HebaruSan** [comment]
If the .version file is incorrect, that's a mod problem, not a CKAN problem. Is that what you're reporting?

**Comment by HebaruSan** [comment]
OK, as far as I can tell, this issue was complaining about the fact that NearFutureProps was being extracted from the download for NearFutureSpacecraft, which includes it as a dependency.

NearFutureProps has its own github, and I've accidentally updated the NetKAN listing to use it (meant to make a pull request for testing, but forgot to click the radio button so it went directly to the master branch), but it only found version 0.2.0 because the later releases don't have assets (just the "source code" downloads).

![image](https://user-images.githubusercontent.com/1559108/35748275-6550338a-0845-11e8-868b-5525ef9b5331.png)

I think I'll try making CKAN-meta entries for the later versions by hand...

**Comment by HebaruSan** [comment]
@yalov, I made some updates. Can you refresh and try again?

**Comment by yalov** [comment]
ok, I see corresponding version.

as I get it, v0.3.0 was released with new StationPartsExpansionRedux but it is unknown should StationPartsExpansion users update NearFutureProps to v0.3 or shouldn't.
