### ISSUE TITLE
USI dependency on firespitter

### ISSUE THREAD

**Issue by M3tal-Warrior** [KSP-CKAN/NetKAN#6376]
Background
----------

**CKAN Version:** 
1.24.0

**KSP Version:** 
1.4.0.2077

**Operating System:** 
Win7 Pro

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
USI Asteroid Exploration Pack
USI Core
USI Exploration Pack
USI FTT
USI Kolonization Systems

Problem
USI already has a working Firespitter Core bundled, yet is dependend on Firespitter Core (which is not up to date)

**Comment by HebaruSan** [comment]
Looks like RoverDude forgot to make an official/public release of FirespitterCore 7.9.0, and just bundled it instead.

The CKAN team can't make a new release of FirespitterCore, and we also can't change USI's metadata since [it's managed by RoverDude via a meta-netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/USI-Core.netkan). I would suggest politely asking RoverDude to please make a GitHub release for FirespitterCore 7.9.0, but you should probably wait a couple of days first in case he's already planning it.

**Comment by linuxgurugamer** [comment]
I just did that
