### ISSUE TITLE
The Sort By Download Size, Doesn't

### ISSUE THREAD

**Issue by StevenBarden** [KSP-CKAN/NetKAN#6611]
I'm sure you know by now, but it's sorting alphabetically, an easy switch in C#. Ty.

Background
----------

**CKAN Version:** 1.24.0

**KSP Version:** 1.4.4.2215

**Operating System:** Win10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Thanks for the report. This was [originally reported on the forum](https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1251-broglio/&page=37&tab=comments#comment-3303380), fixed in #2311.

Download the [latest release](https://github.com/KSP-CKAN/CKAN/releases/latest) for the fix.

**Comment by StevenBarden** [comment]
I apologize for taking your time with this. Thank you.

**Comment by HebaruSan** [comment]
No apology needed, thanks for taking the time.

**Comment by HebaruSan** [comment]
1. Localization problems
   Sorry, I don't know what would cause that (and I don't know which script you're referring to), other than it sounds like some of the stock game files are messed up. If this happened to me, I think I would try checking the integrity of the stock game files to restore them to their pristine state. Steam has an easy way to do this, but if you don't have Steam, simply reinstalling the game might be enough.

2. S.A.V.E. mod file format
   I also don't know the answer to this one, since I haven't tried that mod. I would recommend asking on the [forum thread for that mod](https://forum.kerbalspaceprogram.com/index.php?/topic/94997-142-save-automatic-backup-system-152-3063/). Either the mod author or some of the other users should be able to explain how it works.

3. Installation timestamp suggestion
   I think that idea is on file somewhere here:
   - KSP-CKAN/CKAN#1933
   - KSP-CKAN/CKAN#1155
   - KSP-CKAN/CKAN#1046

4. Hold checked state / ACID test
   Sounds like this is all about losing changes if there's a problem with an install? It sounds like a good idea in the abstract, but I'm not sure how it would be implemented in practice. (And whenever possible, I'd prefer to fix a crash rather than working around it.)
   Please feel free to submit a more detailed enhancement suggestion: https://github.com/KSP-CKAN/CKAN/issues/new

5. You helping
   Of course! CKAN is open source and MIT-licensed and welcomes contributions and pull requests here on GitHub. There are several wiki pages that are intended to help with getting started:

   - https://github.com/KSP-CKAN/CKAN/blob/master/CONTRIBUTING.md
   - https://github.com/KSP-CKAN/CKAN/wiki/New-Developers%27-Guide
   - https://github.com/KSP-CKAN/CKAN/wiki/Developers%27-Guide

   You don't even need to be an official member to get started. I personally submitted several small code fixes before being formally invited to join, and that route remains open to anyone interested.

**Comment by StevenBarden** [comment]
Steven Barden
________________________________

**Comment by StevenBarden** [comment]
1) I wish I'd reviewed more before some points, as I can see many smarter people beat me to them. Actually, I am happy to find this.

2) Until I absorb the start reads, do you target a version of Visual Studio?


________________________________
