### ISSUE TITLE
BetterBurnTime v1.6.1 - Please set minimum KSP version as KSP v1.3.1

### ISSUE THREAD

**Issue by KalSB** [KSP-CKAN/NetKAN#6629]
Firstly many thanks for an amazing tool. I've only recently entered the Kerbal world and already CKAN has become invaluable to me along with many mods from the modding community. THANK YOU!

Background
----------

**CKAN Version:**
1.25.1

**KSP Version:**
1.4.2

**Operating System:**
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

**Affected mods and mod versions:**
BetterBurnTime v1.6.1 by @KSPSnark

Problem
-------

**What steps did you take in CKAN?**
N/A

**What did you expect to happen?**
To be able to install BetterBurnTime v1.6.1 in my KSP v1.4.2 instance (without fiddling with the compatible KSP versions).

According the module changelog and mod forum, BetterBurnTime v1.6.1 was originally released for KSP v1.3.1 and has worked unchanged with all KSP releases since then.

**What happened instead?**
BetterBurnTime v1.6.1 is listed in CKAN as only compatible with only KSP v1.4.4 and not KSP v1.4.2 which I am running (for compatibility with specific other mods) and so is unavailable to install without overriding the compatible KSP versions.

Can you please update the minimum version for this mod in the NetKAN metadata to KSP v1.3.1?

Looking at the changelog, I suspect it would also be backwards compatible with even earlier versions too but this is pure speculation on my part.

Thank you again.

**Screenshots:**
N/A

**CKAN error codes (if applicable):** 
N/A

**Comment by KSPSnark** [comment]
Sorry, I have no clue how CKAN does what it does (have never used it, myself).  The sum total of my involvement with CKAN is that when I host a new mod on SpaceDock, I click the little check-box that asks me whether I want to publish on CKAN.  That's it.  Whatever happens after that point is handled by automatic machinery that's invisible to me.

I can see how this issue would be vexing to someone who mainly uses CKAN, and I'm sorry about that, but since I don't maintain CKAN myself (and don't really have the bandwidth to get involved with it), I'm afraid this one's not something I expect to fix.  Thank you for the kind words, and thank you for taking the time to report the matter (and for making the effort to be detailed and precise about it)-- I'm sorry I can't be of more help.

FWIW, BetterBurnTime doesn't have any dependencies on any other mods and is super easy to install manually.  Just follow the instructions on it and unzip it into your GameData folder.

**Comment by HebaruSan** [comment]
Hi, @KSPSnark! There are ways of solving this that involve you and ways that don't. If you were interested, a [KSP-AVC file](http://ksp.cybutek.net/kspavc/Documents/README.htm) for this mod could effectively announce the game version range that you officially support (currently drawn solely from the single version on SpaceDock). The advantage of this is that CKAN would always reflect your exact intentions, for this version and all future versions, but obviously it's more maintenance for you.

Alternatively, with no changes on your side we can override the versions supported to something like this ("1.4" matches all 1.4.x game versions):

```json
    "ksp_version_min": "1.3",
    "ksp_version_max": "1.4",
```

This might be worth doing, but it presents two problems. First, it might not reflect your intentions (you might want to test on future 1.4.x versions before announcing compatibility). Second, if you someday update the game version on SpaceDock to be 1.5.0 or later, we would have to come back and update the override to reflect that, and there wouldn't be an automated notification to alert us.

The third option, of course, is to say "too bad" and leave it as-is, since this dilemma is not at all unique to this mod. Users have the option to configure additional game versions to consider compatible in the client app, which would allow this and other mods to be installed:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

I hesitate to recommend that, though, since we're talking about a 1.x level difference rather than 1.4.x level; installing 1.4-compatible mods on 1.3 may not be as safe in all instances as it is for BBT.

Just some thoughts to fill in the background here.

**Comment by linuxgurugamer** [comment]
@KSPSnark I would be happy to help  you with the KSP-AVC file.  Once it is set up, all you would have to do is to update the .version file when you release an update.
Let me know

**Comment by KalSB** [comment]
A giant thank you to all who responded, I'm really impressed with what I have seen in the KSP modding community. I may even join in myself once I've played the game more (I'm on my first career mode playthrough right now).

@KSPSnark, I mainly linked you as a polite FYI that there is something happening regarding your mod rather than expecting you to do anything - and why I logged the issue against NetKAN rather than your BetterBurnTime. I totally understand mod authors with limited time who won't want to get involved with a mod management tool they don't use themselves. That said if you did have the time and inclination (and with no expectation on my part), it seems that adding a KSP-AVC file to your mod with the KSP versions supported would be relatively simple and well appreciated by CKAN users as well as users of the KSP Addon Version Checker plugin.

Thanks @HebaruSan and especially @linuxgurugamer for jumping in so promptly and for all you do to support the KSP modding community. I've already noticed this in my limited time getting up to speed with KSP and the various mods out there.
