### ISSUE TITLE
numbering patches for few versions

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6823]
https://github.com/yalov/SpeedUnitAnnex/releases

the patch v1.2.0.1 (KSP 1.4.5) does not show up in the ckan version list.
the patch v1.2.1.1 (KSP 1.5.1) got 1.4.0-1.4.9 range

**Comment by HebaruSan** [comment]
Actually the one that got indexed is 1.2.0.1, but it got listed as 1.2.1.1 because that's the version it has on GitHub.

![image](https://user-images.githubusercontent.com/1559108/48098183-daecad00-e213-11e8-82b9-95e3cee97fc1.png)

The bot only looks at the first asset in a release. Don't try to combine multiple releases into one.

**Comment by yalov** [comment]
I separated them, will they be scanned without epoch?

I already was combining 1.1.3/1.1.4 before, and it was ok...

**Comment by HebaruSan** [comment]
1.2.1.1 will be scanned by the bot the next time it runs. 1.2.0.1 will need to be added manually, I'll take care of that in a couple of minutes.

1.1.3 and 1.1.4 were indexed from SpaceDock, where those versions were not combined:

![image](https://user-images.githubusercontent.com/1559108/48098922-f9ec3e80-e215-11e8-84ff-ac5221206b99.png)

(You switched to GitHub after that, in #6422.)

**Comment by yalov** [comment]
ok, thanks

**Comment by yalov** [comment]
@HebaruSan  1.2.1.1 appears, but has not right ksp version (not 1.5.0-1.5.9), will it be updated later or also need to be changed manually?

**Comment by HebaruSan** [comment]
Give the bot 4 more hours to run.
