### ISSUE TITLE
Discussion: Best Practices for managing mod NetKAN metadata?

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#7101]
G'day,
Raising as issue since nobody seems to be active on IRC and there's a note to raise a Github issue instead.. please let me know if this type of discussion would be better on the Forum Thread instead.

In general it's fairly straightforward, but wondering about some Best Practices for managing the CKAN metadata for mods.

----

What are the pros/cons about hosting NetKAN files myself for the mods I manage (ie, Metanetkan's) versus sending pull-requests against the master NetKAN's in the NetKAN repo?

Seems that if I host them myself, I can easily manage any minor changes and updates without having to wait for a NetKAN developer to review and accept pull requests, and in the event that I totally stuff up or go AWOL, the master NetKAN can be modified to remove link to the Metanetkan to fix things.

----

Both Curse and Spacedock have a mechanism to mark a released Mod as being compatible with a new version of KSP.

So wondering whether it's possible to tag a mod as being compatible with a new version of KSP without having to make a new release which would force a user to re-download a mod just for an updated .version file.

----

Thanks!

**Comment by DasSkelett** [comment]
It's better as a issue here, else we would spam the forum thread with messages and all the users watching it.
I don't have much experience with metadata yet, neither do I maintain any KSP mod, so I can't speak out of a modder's side of view

**Comment by DasSkelett** [comment]
Sorry misclick :/

**Comment by politas** [comment]
It is possible to specify exceptions to the default scraping of KSP version compatibility in the Netkan file for the latest release, and in the .ckan files for old releases.The format is a little finicky, so hosting the Netkan file here is probably better from that regard unless you want to invest a fair bit of time understanding the .netkan structure.

The main reason for self-hosted .netkan files is when you are making fairly substantial changes to the file structure of your mod and need to adjust the install instructions for each release.

**Comment by HebaruSan** [comment]
> So wondering whether it's possible to tag a mod as being compatible with a new version of KSP without having to make a new release which would force a user to re-download a mod just for an updated .version file.

Yes, this is one function of the "URL" property in the .version file (in addition to checking for new releases). If Netkan is able to find a valid .version file at the specified URL, and if both "VERSION" properties are the same, then the game compatibility data from the online file will override the data from the file in the download. I have done this with my mods and it works; this commit:

https://github.com/HebaruSan/Astrogator/commit/0bb22564957534be0b27e7c36780b5c87427b734#diff-9a9e7aa5788fa3e990426009ae6489b5

... triggered this one with no change to the download:

https://github.com/KSP-CKAN/CKAN-meta/commit/f6325402744e593b2d2dc69a9e4804a14f11cbcc#diff-18954f9c2edbcab4d70e187924f7a208

The relevant code lives here:

https://github.com/KSP-CKAN/CKAN/blob/3bc537637e8f4452c9787699045d61b4d869061f/Netkan/Transformers/AvcTransformer.cs#L66-L85

____

As for the question of metanetkans, my mods use them, but I've had second thoughts about that. There's value in the NetKAN database being monolithic, in that we can run searches and scripts if we need to fix or update something, and metanetkans make such tasks more cumbersome.

In addition, metanetkans create the potential to bypass some of the de facto "rules" about metadata, for example that we should use a "depends" property instead of installing bundled mods. Probably very few authors are aware of all such things, so there's some inherent risk in allowing updates without review by a team member.

> without having to wait for a NetKAN developer to review and accept pull requests

Heh, I see it from the other side: mod authors can break their metadata and I can't fix it. :)

That's not to say I'm against metanetkans though. If you see a benefit in it, then go ahead and use one.

**Comment by HebaruSan** [comment]
@mwerle, do you have any remaining questions on this?

**Comment by mwerle** [comment]
Sorry, forgot about this. I've played around with the version file a bit and it all seems to work as expected.

I have no further questions at the moment, thanks for the help :)
