### ISSUE TITLE
Description from the Readme.md

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#7154]
https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN

> if there is a readme.md in the repository, that will be used to create the mod description that users will see, which you can replace with an abstract tag.

possible unintentional, that short repo description on the github, (abstract tag), replaces README.md (description tag) in the GUI

**Comment by yalov** [comment]
I removed github description (abstract), re-netkan-ed, but descripion from the readme.md didn't show up

**Comment by DasSkelett** [comment]
There is some confusing name switching going on:
https://github.com/KSP-CKAN/CKAN/blob/3aa6c51be2fb055d7fed650785882e49c2e114ae/Netkan/Transformers/GithubTransformer.cs#L93-L94
The GitHub description actually is saved in the abstract.
Most mods only have an abstract, no description. In the GUI, both, if existing, are shown below the mod name in the mod info panel.

But I'm not sure if I understand your issue correctly. Can you name an example?

**Comment by yalov** [comment]
just wanted to see how this conversion from the githib_repo/README.md looks like.
ghRepo.Description is an abstract, because it's limited to 344 chars, and suppose to be one/two-liner

Readme.md can be very large, what is not well for the CKAN, but it is convenient for the few sentences with empty lines

**Comment by HebaruSan** [comment]
I've never seen Netkan do anything with a README file, and indeed there is no occurrence of the string 
"README" in is code. Trying to figure out how this text got there:

| Date | Event |
| --- | --- |
| May 9, 2016 | KSP-CKAN/CKAN#1723 added ability to populate `abstract` based on the repo description |
| August 30, 2016 | [Wiki updated](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN/_compare/b9f0dee05e3cfbd4336fd84152740cdae9322a0f...765924173dde6d20854d0fbfd1cbb3bd2e06f1f4) to say the abstract can be populated from `readme.md` |

I think @politas either mis-remembered (almost two months having passed) or thought "repo description" meant "readme.md", since a lot of people describe their repos in that file. I'll post an update with screenshots of the actual field.

**Comment by HebaruSan** [comment]
Pasting images here because you can't paste them directly into the wiki:

![image](https://user-images.githubusercontent.com/1559108/56605090-f2083700-65c8-11e9-9597-cf2cdbe89d5f.png)

![image](https://user-images.githubusercontent.com/1559108/56605100-fa607200-65c8-11e9-9f32-e772dda39392.png)

**Comment by HebaruSan** [comment]
The wiki is now accurate. Thanks for spotting this and reporting it.
