### ISSUE TITLE
KerbalPlanetaryBaseSystems file paths too long to install on Windows

### ISSUE THREAD

**Issue by MeDungGoof** [KSP-CKAN/NetKAN#7305]
I have been dealing with an issue particularly with a certain mod, that I definitely would consider a must-have, and that's the "Kerbal Planetary Base System" mod on CKAN. The error that would occur during the download is this, something regarding the file-name length and destination. Following the error, the CKAN application becomes unresponsive and crashes. This is the error.

![image](https://user-images.githubusercontent.com/52611328/60761459-f617f280-a016-11e9-8a9c-b3c2d44d7236.png)

I took to reddit when i couldn't find a solution, and stumbled upon this thread. https://www.reddit.com/r/KerbalSpaceProgram/comments/81rhvv/issue_installing_mod_with_ckan/

and the thread poster had a similar problem; destination files names were too "large". After a bunch of scrambling around I found and "fix" and its a link that lead to debugs. If I can understand what it's trying to do, I'm assuming it allows CKAN download file names to exceed its normal character limit. But I dont know how to apply it onto my own CKAN application. How can I do this?

EDIT: 
Forgot to add proper links :/ 
Here they are:
**Link to "fix" (debugs)** https://github.com/KSP-CKAN/CKAN-meta/commit/620f9ba0a44c3dc583feb2319046dafa3072df90

**Comment by DasSkelett** [comment]
The issue you found on Reddit is a very different one, it came up because the mod author reuploaded a release file after CKAN indexed it, so the hashes and the folder size that was known to CKAN wasn't right anymore.

Your problem is, that Windows only allows the length of a path to any file to be less than 260 characters. It's a very legacy restriction where no one knows why it is still there as default...
So nothing that can be fixed from CKANs side.

There are several ways for you to fix this problem:
1) Move your KerbalSpaceProgram folder somewhere else, with a shorter path:
	Instead of `C:/Users/*****/Desktop/Kerbal.Space.Program/***` to `C:/KSP`
2) If you are using Windows 10 with the Anniversary Update installed, see this guide how to increase the max path length: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
3) Ask Nils to rename or redo the folder structure of KPBS to have shorter folder and file names
4) Ask Microsoft to disable this dump restriction by default
5) Use any Linux distribution (or macOS probably works too) :)

I can't make out whether this is the case for your KSP path or your cache path.
I'm assuming it's your KSP path. But it only matters if you choose the first option.
If you have choosen the first option, and the issue still occurs, try the same with youe cache folder. You can check the CKAN settings to find out where it is located, and don't forget to change it there after you moved it.

If you still have questions, or didn't understand something, just ask.

**Comment by HebaruSan** [comment]
I tried installing the most recent version of that mod for KSP 1.3.1 in `C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\PlanetaryBaseInc`, and the longest path was 191 characters. This may be mostly a problem with a very long game folder path.

- `C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/PlanetaryBaseInc/./ModSupport/Parts/DeepFreeze/Spaces/Cry-5000Internals/CRY-5000Internal_JSIATP_DM_Addon_Overlay.mu`

**Comment by MeDungGoof** [comment]
> The issue you found on Reddit is a very different one, it came up because the mod author reuploaded a release file after CKAN indexed it, so the hashes and the folder size that was known to CKAN wasn't right anymore.
> 
> In your case the problem is, that Windows only allows the path length to any file on your PC to be less than 260 characters. It's a very legacy restriction where no one knows why it is still there as a default...
> And KPBS wants to install files that have very long names, with a very long path.
> Windows doesn't allow this.
> It's nothing that can be fixed from CKANs side.
> 
> There are several ways for you to fix this problem:
> 
> 1. Move your KerbalSpaceProgram folder somewhere else, with a shorter path:
>    Instead of `C:/Users/*****/Desktop/Kerbal.Space.Program/***` to `C:/KSP`
> 2. If you are using Windows 10 with the Anniversary Update installed, see this guide how to increase the max path length: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
> 3. Ask Nils to rename or redo the folder structure of KPBS to have shorter folder and file names
> 4. Ask Microsoft to disable this dumb restriction by default
> 5. Use any Linux distribution (or macOS) :)
> 
> So your best chances are with 1) and 2).
> 
> I can't make out whether this is the case for your KSP path or your cache path.
> I'm assuming it's your KSP path. But it only matters if you choose the first option.
> If you have choosen the first option, and the issue still occurs, try the same with youe cache folder. You can check the CKAN settings to find out where it is located, and don't forget to change it there after you moved it.
> 
> If you still have questions, or didn't understand something, just ask.

Fix number (1) definitely helped me out! I downloaded a cracked version of KSP on a seperate website, seems to me that it didn't create an independent file in my C:/ Drive, that would have created a much shorter path than adding the entire game file to an already crowded C:/Users/*****/Desktop/Kerbal.Space.Program/***. 

Anyways, thank you for the help. I guess I can finally install it now, and everything is in a shorter path. Thank you for the help!

**Comment by HebaruSan** [comment]
> I downloaded a cracked version of KSP

**Please do not pirate KSP, or talk about pirating KSP, or ask for help with a pirated copy of KSP here.**
