### ISSUE TITLE
[Mod] Request to track new fork B9-PWings-Fork for KSP 1.8.1

### ISSUE THREAD

**Issue by jrodrigv** [KSP-CKAN/NetKAN#7486]
AVC version file for tracking purposes:
https://raw.githubusercontent.com/jrodrigv/B9-PWings-Fork/master/GameData/B9_Aerospace_ProceduralWings/Plugins/B9_Aerospace_WingStuff.version

Mod info
--------
* Mod name: B9-PWings-Fork
* Author(s): Jebman82,bac9,Crzyrndm,jrodrigv
* License: https://raw.githubusercontent.com/jrodrigv/B9-PWings-Fork/master/LICENSE
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/175197-13x14x15x16x17x-b9-procedural-wings-fork-go-big-or-go-home-update-40-larger-wings/
* Download: https://github.com/jrodrigv/B9-PWings-Fork/releases/tag/V0.92

**Comment by DasSkelett** [comment]
Their has been some switcharoo going on.
@HebaruSan already changed the netkan to reference your repo some time ago, and lateron @linuxgurugamer switched it again to another maintainer, probably without your knowledge?
https://github.com/KSP-CKAN/NetKAN/commits/master/NetKAN/B9-PWings-Fork.netkan

**Comment by DasSkelett** [comment]
Ah, it looks like you and Jebman are switching maintainership every now and then.
What about creating a common GitHub organization? This way the repository could stay the same independent of who is currently doing the releases.

**Comment by jrodrigv** [comment]
Yes, I'm fine with that. In fact, if the previous maintainer wants to do a new release and override the tracking of my fork I will be totally fine with it.

For the moment, I'm just notifying this to you guys so that we can provide a KSP 1.8.1 compatible release.

**Comment by DasSkelett** [comment]
@Rafterman82 are you okay with changing the fork back to @jrodrigv again?
Or should we find another solution?

While changing out the kref does work as long as both of you keep the same versioning scheme, it's not the ideal solution IMHO.

**Comment by DasSkelett** [comment]
Since @Rafterman82 didn't reply yet, and you guys are  all understandably eager to get the 1.8 version on CKAN, I'd say we are okay to switch the fork now.

When @Rafterman82 returns, you can try to find a more permanent solution, like one person giving the other push access to his repository for example.

**Comment by DasSkelett** [comment]
Done in #7502

**Comment by Rafterman82** [comment]
Hi Guy,

What is it you need? Happy to merge in stuff, grant permission. Have no issue with anything you wanna do. Just let me know if you need me to action giving someone access!

Cheers

Paul Rafter

Sent from my iPhone please excuse any typos.

T: 07802 699 209
E: paulrafter@hotmail.com
S: paul_rafter

Please consider the environment - only print this email if absolutely necessary

On 16 Nov 2019, at 14:00, DasSkelett <notifications@github.com> wrote:

﻿

Since @Rafterman82<https://github.com/Rafterman82> didn't reply yet, and you guys are all understandably eager to get the 1.8 version on CKAN, I'd say we are okay to switch the fork now.

When @Rafterman82<https://github.com/Rafterman82> returns, you can try to find a more permanent solution, like one person giving the other push access to his repository for example.

**Comment by DasSkelett** [comment]
@Rafterman82 I just see that you already merged @jrodrigv PR.
@jrodrigv also did a release on his fork of B9-PartWings fork for KSP 1.8.1.
We just changed the NetKAN to point to his repository, so this version can be indexed by CKAN.

Since it looks like you two are alternately active maintaining this mod and doing releases, you both could work together on a single repository. This would ease it for us (CKAN) as we don't need to change the fork every time, and probably for you two too, and for users searching the newest version.

So my suggestion is you @Rafterman82 give @jrodrigv push access and permissions to release new versions on your repository.

**Comment by HebaruSan** [comment]
In case it's not clear what that means, here are some references from GitHub's documentation:

- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-organizations
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

For example, the RealismOverhaul team collaborates on this organization; once they are added as members, they are able to work on any of the respositories it contains, including creating new releases:

https://github.com/KSP-RO

**Comment by DasSkelett** [comment]
Actually it's also possible to give people push access on non-organization/personal repositories: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

But this page is not very clear about the permissions that are granted to a collaborator.

**Comment by Rafterman82** [comment]
Cool, just driving home will sort that in about an hour 👍🏻

Paul Rafter

Sent from my iPhone please excuse any typos.

T: 07802 699 209
E: paulrafter@hotmail.com
S: paul_rafter

Please consider the environment - only print this email if absolutely necessary

On 16 Nov 2019, at 14:47, DasSkelett <notifications@github.com> wrote:

﻿

Actually it's also possible to give people push access on non-organization/personal repositories: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

But this page is not very clear about the permissions that are granted to a collaborator.

**Comment by Rafterman82** [comment]
Hey guys, added you all as collaborators, should give you more flexibility. I may do another release soon to ensure everything is compatible. But also keeping a close eye on KSP2 :)
