### ISSUE TITLE
Inline Ballutes changed to make FAR a depend, why?

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7572]
Apparently, sometime in the past day, The InlineBallutes netkan got changed to make FAR a dependency.
I dont know why you did that, but you are causing problems for me and people who use this mod

Hopefully it was just a mistake

LGG

**Comment by HebaruSan** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/121162-130-inline-ballutes-ib-v128-30052017/

![image](https://user-images.githubusercontent.com/1559108/70868556-8869de00-1f47-11ea-8e5b-e365fe080cdb.png)

I thought that was listing FAR as a dependency rather than specifying dependencies **if** FAR is installed. Yes we can undo it.

**Comment by HebaruSan** [comment]
Fixed in https://github.com/KSP-CKAN/NetKAN/commit/277decd8ff6836dc07b1d6563d2e4478bcb44b59#diff-8e7bdb2f2ed842f5edd873459c6d77c5

**Comment by linuxgurugamer** [comment]
Thank you.

I would have done it myself, but didn't want to step on your changes

**Comment by linuxgurugamer** [comment]
And I'll update the OP, it does look confusing
