### ISSUE TITLE
[Bug] Spaceplane Corrections is incorrectly showing as outdated, and there are two versions of it.

### ISSUE THREAD

**Issue by Avera9eJoe** [KSP-CKAN/NetKAN#7672]
Background
----------
* Operating System: Windows 10 Pro
* CKAN Version: 1.27.0
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
**Describe the bug** Spaceplane Corrections is incorrectly listed in CKAN, saying that it is outdated when it in fact is up to date. SpaceDock lists it as as updated for 1.8.1 and added to CKAN, but in CKAN the metadata says the max version is 1.3.9.

Additionally, there is a defunct version of the mod called "Space Plane Color Corrections" which is also in CKAN. I renamed the mod early on in development (after I had added it to CKAN), and that version is no longer needed. It is safe to remove it.

**Steps to reproduce**
* Search "Spaceplane Co" in CKAN
* See that there are two mods called "Space Plane Color Corrections" and "Spaceplane Corrections"
* Note that "Spaceplane Corrections" is incompatible with 1.8.1 when it should be marked as compatible.

**Expected behavior**
* "Spaceplane Corrections" should be compatible with KSP 1.8.1.
* "Space Plane Color Corrections" should not be in CKAN.

**Screenshots (if applicable)**
--

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
This mod has been indexed with this identifier a long time ago.
For whatever reason, the netkan has a version override to set the compatibility for v0.19 to KSP 1.3 only.
In #7361 this has likely been overlooked. It's time to remove that override.

Regarding "Space Plane Color Corrections":
Is there any harm that it exists? Thanks to the archive.org fallback, you can still install it. Someone doing a retro-session (or someone still playing on 1.0.5 for whatever reason) might appreciate still being able to download it.
Since it is only set as compatible with KSP 1.0.5, there's no risk it gets accidentally installed instead of SpaceplaneCorrections.

But, maybe we could just switch out the identifier to `SpaceplaneCorrections` and replace the download link with the one for archive.org, so this SPPCC version shows up as older version of SpaceplaneCorrections.
