### ISSUE TITLE
[Bug] SCAN Sat Repro outdated

### ISSUE THREAD

**Issue by matutanos** [KSP-CKAN/NetKAN#7691]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.27.0.0
* KSP Version: 1.8.1.2694

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
**Describe the bug**
SCANsat mod is up to v19.0 ( https://github.com/S-C-A-N/SCANsat/releases/tag/v19.0 ) but according to CKAN only up to v18.14 is available.

I looked around where to report this, but only the in-CKAN "Report issue with mod metadata" seemed halfway appropriate.

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
We use the SpaceDock page to index the releases of this mod: https://spacedock.info/mod/129/SCANsat
It's still missing the v19.0, probably because the version is also marked as pre-release on GitHub.
Looks like DMAgic doesn't want the broad audience to use the new version yet. I found the following note in the forum thread:
>  There is a dev version up on the the dev thread. It is mostly meant for testing the upgrade process at this point, and you can't downgrade to a previous version without losing saved scan data, so proceed with caution. 

https://forum.kerbalspaceprogram.com/index.php?/topic/72679-180-scansat-v1814-real-scanning-real-science-at-warp-speed-october-28-2019/&do=findComment&comment=3735648

> I looked around where to report this, but only the in-CKAN "Report issue with mod metadata" seemed halfway appropriate.

Yep, this is the right place :+1:

**Comment by HebaruSan** [comment]
Yeah, looks like everything is working correctly and the reason it's not listed is because the author doesn't want it in common use. Let us know if this persists after the forum thread gets updated with this new version (but wait a few hours first).

![image](https://user-images.githubusercontent.com/1559108/74368316-07896000-4d99-11ea-9b36-5009b12af89b.png)

**Comment by Artemonim** [comment]
SCANsat from may 31 has version 20 on the SpaceDock, but 18.14 in CKAN.

**Comment by DasSkelett** [comment]
@Artemonim different problem, but also known: https://github.com/S-C-A-N/SCANsat/pull/371
We will never see v20.0 on CKAN, we have to wait for a new release with fixed version file.
