### ISSUE TITLE
AnyResContinued has max version set automatically because it's on SpaceDock

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7697]
This happens on a lot of mods, but here is one case:

AnyRes, the KSP_VERSION_MIn is 1.8.0.
CKAN allows it to be installed

When launching game, I get a warning:
![image](https://user-images.githubusercontent.com/1630166/74490055-561c2480-4e95-11ea-9f78-ec9332f9c262.png)

**Comment by linuxgurugamer** [comment]
Why doesn’t the ckan bot respect the .version file?  This seems like a big bug, and your solution will require that I update ALL of my mods to use github.  This is not ideal, since the advantage of Spacedock is that when updating a mod there, the indexing gets updated almost immediately, while github has a significant delay.
To me, it seems that a .version file should override the Spacedock setting

**Comment by linuxgurugamer** [comment]
I just reviewed #7166 and while I still think its bad logic, I will have to spend several hours updating all of my .netkan files.
This is a real problem because I depend on several values being read from the Spacedock settings.

**Comment by HebaruSan** [comment]
In how many cases is an unbounded range actually appropriate? Didn't you have a bunch of mods for 1.7 that broke with 1.8's Unity upgrade?

**Comment by HebaruSan** [comment]
The forum thread implies that **this** mod is one of them:

![image](https://user-images.githubusercontent.com/1559108/75097876-94a59380-55a7-11ea-85f6-9303f0eb94ed.png)

**Comment by HebaruSan** [comment]
Historical side note, the current behavior is from KSP-CKAN/CKAN#1299 (4.5 years ago)

**Comment by linuxgurugamer** [comment]
> In how many cases is an unbounded range actually appropriate? Didn't you have a bunch of mods for 1.7 that broke with 1.8's Unity upgrade?

Yes, but I have accepted the fact that I don't have time to rebuild all mods every release.  It's only a real problem with the engine upgrade, 1.8 to 1.9 is no problem

**Comment by HebaruSan** [comment]
Just curious, are you aware that you can use remote version files to update compatibility after a release, without having to rebuild anything? That might be the best solution here.

Example: I do this with Astrogator. If you [download v0.10.0](https://github.com/HebaruSan/Astrogator/releases/download/v0.10.0/Astrogator.zip), it contains this version file indicating compatibility only with KSP 1.8:

```json
{
	"NAME": "Astrogator",
	"URL": "https://raw.githubusercontent.com/HebaruSan/Astrogator/master/Astrogator.version",
	"DOWNLOAD" : "https://github.com/HebaruSan/Astrogator/releases",
	"GITHUB": {
		"USERNAME": "HebaruSan",
		"REPOSITORY": "Astrogator",
		"ALLOW_PRE_RELEASE": false
	},
	"VERSION": {
		"MAJOR": 0,
		"MINOR": 10,
		"PATCH": 0
	},
	"KSP_VERSION_MIN": {
		"MAJOR": 1,
		"MINOR": 8
	},
	"KSP_VERSION_MAX": {
		"MAJOR": 1,
		"MINOR": 8
	}
}
```

The `"URL"` property points here, which contains an updated copy of the file with `KSP_VERSION_MAX.MINOR` changed from 8 to 9:

https://raw.githubusercontent.com/HebaruSan/Astrogator/master/Astrogator.version

```json
{
	"NAME": "Astrogator",
	"URL": "https://raw.githubusercontent.com/HebaruSan/Astrogator/master/Astrogator.version",
	"DOWNLOAD" : "https://github.com/HebaruSan/Astrogator/releases",
	"GITHUB": {
		"USERNAME": "HebaruSan",
		"REPOSITORY": "Astrogator",
		"ALLOW_PRE_RELEASE": false
	},
	"VERSION": {
		"MAJOR": 0,
		"MINOR": 10,
		"PATCH": 0
	},
	"KSP_VERSION_MIN": {
		"MAJOR": 1,
		"MINOR": 8
	},
	"KSP_VERSION_MAX": {
		"MAJOR": 1,
		"MINOR": 9
	}
}
```

Netkan reflects that update (as does KSP-AVC):

https://github.com/KSP-CKAN/CKAN-meta/blob/97b275ff21e4d42225557e5677f97b4ca2e71fe4/Astrogator/Astrogator-v0.10.0.ckan#L10-L11

```json
    "ksp_version_min": "1.8",
    "ksp_version_max": "1.9",
```

If a mod released for a previous version of KSP turns out to be compatible with a newer version, this is a very convenient way to handle that.

**Comment by HebaruSan** [comment]
After #7729 and https://github.com/KSP-CKAN/CKAN-meta/commit/0a8e6fcf39d5a96804c9bee09622a787b61f6c26 this module now has no upper limit to its compatibility. The complaint here is resolved (even though this will probably come back to bite us when people install this plugin on a future KSP version with which it will be incompatible).
