### ISSUE TITLE
[Mod] Awesome Modded Parts v1.1.1

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7744]
Mod info
--------
* Mod name: Awesome Modded Parts v1.1.1
* Author(s): [xxnoobintrainingxx](https://www.curseforge.com/members/xxnoobintrainingxx)
* License: GNU LESSER GENERAL PUBLIC LICENSE
* Homepage: https://www.curseforge.com/kerbal/ksp-mods/awesome-modded-parts
* Download: https://www.curseforge.com/kerbal/ksp-mods/awesome-modded-parts/files

**Comment by HebaruSan** [comment]
Curse hosting doesn't work anymore since they decided to enable CloudFlare bot detection, see https://github.com/KSP-CKAN/NetKAN/issues/7446#issuecomment-548458430 and [the wiki](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#curse-guide). Would you be willing to upload this to SpaceDock or GitHub?

**Comment by HebaruSan** [comment]
Looks like we can't index this. It's on Curse, there's no alternate download, and the author isn't available to add an alternate host.
