### ISSUE TITLE
[Mod] Fuel Tank Expansion Rebuilt

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7801]
Mod info
--------
* Mod name: Fuel Tank Expansion Rebuilt
* Author(s): linuxgurugamer
* License: CC-BY-NC-SA-4.0
* Homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/161093-12-13-beta-release-munar-industries-modular-fuel-tank-expansion-rebuilt/
* Download: https://spacedock.info/mod/1396/Fuel%20Tank%20Expansion%20Rebuilt/download/0.9.7

**Comment by HebaruSan** [comment]
@linuxgurugamer, do you want this mod on CKAN?

**Comment by linuxgurugamer** [comment]
Yes, it used to be on

**Comment by linuxgurugamer** [comment]
Just checked, this mod IS in CKAN, called Fuel Tank Expansion Rebuilt

**Comment by linuxgurugamer** [comment]
> ## Mod info
> * Mod name: Fuel Tank Expansion Rebuilt
> * Author(s): linuxgurugamer
> * License: CC-BY-NC-SA-4.0
> * Homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/161093-12-13-beta-release-munar-industries-modular-fuel-tank-expansion-rebuilt/
> * Download: https://spacedock.info/mod/1396/Fuel%20Tank%20Expansion%20Rebuilt/download/0.9.7

Please note  that all of my mods are in CKAN, if you don't see it, then ask for help.
Also, it's generally a good idea to ask the author if they would want a mod in CKAN, rather than post a request directly.  @HebaruSan is great at following up, but he shouldn't have to do that on things like this.

If you still can't get it in CKAN, please contact me on the KSP forums, or even when I stream on Sunday or Monday evenings.  I'm always happy to help, and will stop a stream to help if you need it.

**Comment by HebaruSan** [comment]
Good catch, I didn't spot that because the identifier is MunarIndustriesFTX, see #5567.
