### ISSUE TITLE
Mod pack Interfering with kerbalx.com

### ISSUE THREAD

**Issue by TheKurgan** [KSP-CKAN/NetKAN#7841]
As the subject states, mod packs are interfering with parts of KerbalX.

This mod pack (Airship Pirates KSP Modpack) that is available on CKAN replaced BDArmory Continued on EVERY craft on KerbalX. This leads to confusion especially since the link leads to a dropbox with outdated mods.

Because KerbalX uses CKAN's listings to find out about mods, this mod pack ended up being assigned parts that belong to BDAc.

Could you please remove Airship Pirates KSP Modpack?

Thanks.

**Comment by HebaruSan** [comment]
@TheKurgan, can you please share a link to one of the craft that is affected by this? The description says "EVERY craft", but I checked several and didn't see Airship Pirates mentioned.

**Comment by HebaruSan** [comment]
Still looks like a KerbalX bug. The APModpack mod does not install any BDArmory files, so it shouldn't own them in KerbalX's database. My guess is KerbalX is just examining the ZIP without looking at the `"install"` stanzas in the CKAN metadata. I'll reach out to katateochi to confirm...

**Comment by HebaruSan** [comment]
... katateochi has essentially already confirmed this is a KerbalX problem and worked on a fix:

https://forum.kerbalspaceprogram.com/index.php?/topic/84389-kerbalxcom-craft-mission-sharing/&do=findComment&comment=3770366

So that should address the issue the OP had here.

As for whether `APModpack` should be de-listed from CKAN, as far as I can tell the metadata is valid, the download still works, and it's properly marked for KSP 1.1.3, so it looks OK at first glance. There were allegations of license violation on the KerbalX forum thread, so I'll see what I can find about that...

**Comment by TheKurgan** [comment]
Cheers, thanks for looking into it, I appreciate it.
Sorry I didn't reply... was trying to get some exercise during this crap time lol.

**Comment by HebaruSan** [comment]
I think I've confirmed that KerbalX's parser doesn't handle `"install"` stanzas. It extracts and parses **all** cfg files in each download ZIP. This could be a serious problem for many mods, except I think it's somewhat rare to bundle part mods as compared to plugins.

https://github.com/Sujimichi/KerbalX/blob/6fd566439361e3bb2fa55237b079717d606301b3/lib/KerbalX/ckan_reader.rb#L318-L324

Thanks for bringing this to our attention. I might be able to submit a fix to katateochi if I can manage to comprehend all this Ruby...
