### ISSUE TITLE
Not a bug so much as a question

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8041]
I got told last night that because an update to WaypointManager, in the source repo, had a .version file in the root as well as in the GameData directory, that CKAN was unhappy.

I don't understand why CKAN is looking at the source repo and not the release file.  Am I wrong?

Line in question:

  "$vref": "#/ckan/ksp-avc",

**Comment by DasSkelett** [comment]
You are correct that NetKAN first only looks at the version file in the release zip. Multiple version files in the release zip _can__ cause errors, but not multiple version files in the source repo.

The only time it checks version files in repositories (or other places online) are if the `URL` property is specified. But in that case the inflator looks at the exact url that is specified, and another version file in a different place doesn't affect it at all.

But the one of WaypointManager points to ksp.spacetux.net, so in this case it doesn't even look at the repository at all.

We got inflation _warnings_ for that until 5 days ago since ksp.spacetux.net was unreachable. These were only warnings though, and the inflation still succeeded, just without remote version file checking.

So not sure what whoever told you that meant, as of right now everything is perfectly fine.

**Comment by HebaruSan** [comment]
> I got told last night that because an update to WaypointManager, in the source repo, had a .version file in the root as well as in the GameData directory, that CKAN was unhappy.

Yeah, whoever told you that thinks they know more than they know. CKAN doesn't scan GitHub repos (other than looking for releases) or care about their layout. If this was in a forum thread, post a link and we can go straighten them out.

**Comment by linuxgurugamer** [comment]
Ok,thanks.  They told me on stream and I panicked a bit
