### ISSUE TITLE
Please mark my version of the RCS Build Aid Continued to be deprecated, so that it won't show up for new installs

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8260]
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Your RCSBuildAidCont is only compatible up to KSP 1.8, so installations >= KSP 1.9 should already only "see" the original RCSBuildAid.
We don't really have a "deprecated" flag we can set for modules. We could however add a `"replaced_by": "RCSBuildAid"`, so that those upgrading their installs from KSP 1.8 to e.g. KSP 1.10 get a checkbox to replace RCSBuildAidCont with RCSBuildAid.

**Comment by HebaruSan** [comment]
Yeah, it doesn't look like any action is needed here. Especially if you're not taking this down from SpaceDock.

- https://spacedock.info/mod/1547/RCS%20Build%20Aid%20Continued
