### ISSUE TITLE
Wild Blue Industries support concerns

### ISSUE THREAD

**Issue by TheDogKSP** [KSP-CKAN/NetKAN#8270]
Mod info
--------
* Mod name: Community “Playmode USI” for Wild Blue Industries mods
* Author(s): TheDog
* License: GPL v3
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/198964-community-%E2%80%9Cplaymode-usi%E2%80%9D-for-wild-blue-industries-mods/
* Download: https://github.com/TheDogKSP/WBIPlaymodeUSI
* requires: Module Manager (not bundled)
* suggests: WBI Pathfinder, MOLE, DSEV, Buffalo, USI LS, USI MKS

Hi guys,

I would like to clarify with you whether it is feasible for my just released mod ("Community Playmode "USI" for Wild Blue Industries mods) to be listed on CKAN.

The mod is basically just configurations for WBI (Pathfinder, MOLE, Buffalo, DSEV).
However, I am using Angel-125's feature of defining a switchable "playmode" instead of just MM patching some parts.

Hence, there is a special requirement for updating the installed mod on a users's install, and I am not sure whether this is the way that CKAN operates:
* my files are all delivered as "inactive", having  a .txt extension. Thus they are NOT loaded by KSP at startup.
* using the WBI playmode switcher, all files belonging to different (WBI delivered) playamodes are then "inactivated" (changed from .cfg to .txt), and the selected playmode is activated (files changed from .txt to .cfg), and hence loaded by KSP the next startup.
* WBI mods usually come with playmode "ClassicStock" active (.cfg), and all other as inactive (.txt)
* Hence, on an install with this USI playmod active, updating the mod requires COMPLETE DELETION OF THE PREVIOUS INSTALL (folder GameData/WildBluePlaymodeUSI), and only then unpacking and copying the new files (which will again be .txt).
* Otherwise there would be duplicate files (.cfg from previous install, and .txt from update), and the playmode switcher would fail renaming files upon playmode change

I am also not sure if you guys a aware, but this already applies to most WildBlue mods, such as Pathfinder, MOLE, etc.!
They may never be updated by "just unpacking and copying over" a new release, instead they should be fully removed first.

Let us please discuss this before adding my playmode mod to CKAN, otherwise borked installs would just cause support issues for you and me...

Cheers, 
TheDog

**Comment by HebaruSan** [comment]
Yikes, that file renaming scheme is highly irregular and prone to throwning wrenches in any other software that so much as steals a glance at those files. I can imagine all sorts of difficulties due to that...

1. Install one or more such mods (so a default .cfg file and some alternate .txt files)
2. Use the mod to rename the default to .txt and some alternate to .cfg
3. Now CKAN has no idea that the new .txt and .cfg files are still part of the original mod that installed their other filenames
4. Almost anything done now will cause problems:
  - Remove one of the source mods: CKAN will try to delete the original files because it has no way to know their "current" names, and the renamed copies will stay in place, likely still affecting gameplay
  - Upgrade the source mods to new versions: CKAN will try to remove the original filenames and replace them with new copies, it the renamed copies of the older version remaining in place as well
  - Install a new WBI mod: The "default" mode will be active instead of the alternate mode chosen by the player in step 2 (maybe the core logic checks for this and renames at game startup?)

Thanks for explaining this. No wonder @Angel-125 was upset with CKAN way back when, the user experience must have been (be?) abysmal for anyone switching to alternate configs.

@linuxgurugamer, did you devise a solution for this before re-indexing these mods in #7982, #8057, #8058, and so on? I believe you exchanged PMs with Angel, but I don't know whether this topic came up.

@TheDogKSP as for your mod specifically, it sounds like it would be no better or worse than the current support for these mods. If you want to add it to CKAN, we can look into it. If we manage to find a way to make this all work out, we can address all such mods at once.

**Comment by TheDogKSP** [comment]
I guess we better wait with adding this you/we have mentally sorted out whether it is even a good idea to have such mods on CKAN. I'll recommend manual install at the moment to everyone, and will highlight in red the specific update requirements (when there is a new release).

Sorry for kicking the hornet's nest, lol... since Pathfinder etc have been on CKAN for ages I was actually hoping that you'd said "yeah, we now, we configure the .netkan to do the clean delete & reinstall"...
now, i guess, that's not how it works...

**Comment by HebaruSan** [comment]
> since Pathfinder etc have been on CKAN for ages I was actually hoping

We can only fix problems we know about. I haven't been on the team forever, but I've done a fair amount of reading old discussions (which tend to be very light on details, see #4294, #4296, KSP-CKAN/CKAN#1890), and this is the first time I've seen an actual explanation of this.

**Comment by HebaruSan** [comment]
I can imagine ways to "CKAN-ize" this stuff:

- A `WildBlue-PlayMode` virtual module to be added to the `provides` and `conflicts` lists of all mods that include "play modes"
- All such modules install .cfg files instead of .txt
- If a mod includes multiple "play modes", we would create a separate CKAN-module for each one and select out the appropriate cfg files in the `install` stanzas
- The main WBI mods would then have `WildBlue-PlayMode` added to their `depends` lists

This way only one "play mode" would be active at a time, managed and enforced via CKAN. You would choose which one to use when installing any WBI mod, and if you wanted to switch, you could uninstall and reinstall and choose differently. If we wanted to go completely over the top, we could use the `install[].as` property to individually rename every .txt file in the existing modules to .cfg one by one (maintenance nightmare, do not do this).

But if a significant technical investment has already been sunk into the current system (as I assume it has), then the migration costs would make this a very hard sell, especially if it was seen as "just for CKAN". More brainstorming needed.

**Comment by HebaruSan** [comment]
@TheDogKSP, do you happen to have an idea of how many "play modes" there are for WBI mods at this point? Are we talking 1-5, 5-20, 20+? And how many authors are there? I hope you don't mind if we pick your brain since you seem to be involved in that milieu.

**Comment by HebaruSan** [comment]
I see 4 "play modes" in WildBlueTools, plus a Common folder:

![image](https://user-images.githubusercontent.com/1559108/102957349-d4772900-449f-11eb-96e9-fd55f0c0e74a.png)

**Comment by TheDogKSP** [comment]
I think it is four:
Classicstock, crp, pristine and simple.

Common is always active and not not a playmode.

To my knowledge i am the first one to ever define his own "external" playmode using angels's mechanics...

**Comment by HebaruSan** [comment]
OK, I see now, the cfg in ClassicStockResources says it extends Classic Stock. So extending the CKAN-ization idea above, it would depend on `WildBlue-PlayMode-ClassicStock` rather than providing `WildBlue-PlayMode` itself.

**Comment by TheDogKSP** [comment]
That sounds right to me, yes.
So if i understand correctly:
Via ckan install you would "separate" the playmodes into individual, conflicting, packages so that only one is installed at a time - and in its active form.
So a user would not use the wbi playmode switcher, but ckan instead to switch playmodes.

To me that seems a good solution, as it avoids problems which come from the switcher, such as duplicate files after updates.

**Comment by TheDogKSP** [comment]
One problem though:
Playmode classicstock for example is used by: pathfinder, mole, dsev, buffalo

And they all can be installed independently of each other.
So i guess the playmode must be "provided" by the wildbluetools package, and "required" by pathfinder, mole, etc...

**Comment by HebaruSan** [comment]
Oh that's kind of gross. @linuxgurugamer missed two of the older identifiers when re-indexing these, so now they're duplicated :(

![image](https://user-images.githubusercontent.com/1559108/102992969-ea0d4280-44e1-11eb-8060-c2cd02915039.png)

**Comment by HebaruSan** [comment]
BTW "Fertilzer" is misspelled, noticed that while scrolling through the metadata to rename all the files.

**Comment by TheDogKSP** [comment]
Good catch, thx!
Its just the filename though, so no need to correct. Resource name inside is correct, luckily.
