### ISSUE TITLE
[Bug] DeepFreeze has BackgroundResources incorrectly marked as a dependency

### ISSUE THREAD

**Issue by LouisB3** [KSP-CKAN/NetKAN#8271]
Background
----------
* Operating System: Windows (probably any)
* CKAN Version: 1.29.2 (probably any)
* KSP Version: 1.10.1 (probably any)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

yes, but that's not relevant here

Problem
-------
See JPLRepo/DeepFreeze#96. "Background Resources" is marked as a dependency for DeepFreeze by CKAN but is not required to run DeepFreeze, per JPLRepo.

**Comment by HebaruSan** [comment]
This was added in #7277 because DeepFreeze started bundling BackgroundResources, which caused conflicts with BackgroundResources itself, see #7276. Checking again now, **DeepFreeze _still_ bundles BackgroundResources**. The installation instructions on the forum thread simply say "Unzip into your Game install directory", which would result in the bundled BackgroundResources being installed. Until that comment by the author on the other issue, there was no indication this was optional.

Any idea why this bundling started?

**Comment by DasSkelett** [comment]
I guess it's more meant as a should-have recommendation, and is not actually a hard dependency.
Different authors, different bundling habits...

**Comment by LouisB3** [comment]
It appears that BackgroundResources provides additional optional functionality to DeepFreeze. I am basing this on the [forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/112328-110x-deepfreeze-v0290-17th-oct-2020/) including the changelog, which refers to JPLRepo's BackgroundResources replacing the defunct BackgroundProcessing mod.
```
V0.26.0.0
Re-compile for KSP 1.7.2 and above.
Added BackgroundResources processing. This is a module also distributed with my TAC LS mod. It will do EC processing for DeepFreezer parts that
are on unloaded vessels (not the active vessel). You can turn it off in the Difficulty settings. It also does unloaded EC production for all vessels.
```

**Comment by HebaruSan** [comment]
Turns out this was wrong, it **was** supposed to be a dependency all along.

https://forum.kerbalspaceprogram.com/index.php?/topic/112328-112x-deepfreeze-v0310-12th-sep-2021/&do=findComment&comment=4132175
