### ISSUE TITLE
ToolbarController is marked in CKAN as max version 1.10.0

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8333]
The .version file for the ToolbarController does not have a max version.  This apparently is causing issues, I've had a few requests to update it.
If this is as intended, then what should I do to get a mod updated for 1.11 so I don't have to keep bugging you ?

Thanks

**Comment by DasSkelett** [comment]
See #7166, https://github.com/KSP-CKAN/CKAN-meta/pull/1471 and https://github.com/KSP-CKAN/NetKAN/issues/7697

It is still the same reason and it will always be the same reason. NetKAN combines the version ranges from the version file and SpaceDock. If no `KSP_VERSION_MAX` is set in the version file, NetKAN will take the version from SpaceDock as `ksp_version_max`.

Yes, this is intended, this is how it works since 5 years.

> what should I do to get a mod updated for 1.11 so I don't have to keep bugging you ?

Update the compatibility on SpaceDock.
Alternatively:

> Recommendation: revert #7032 and #6659. If you want an open-ended version range defined completely by the AVC file, then a host that requires selection of the compatible game version is not for you. GitHub is a better fit.

(https://github.com/KSP-CKAN/NetKAN/issues/7166#issuecomment-487130814)

**Comment by HebaruSan** [comment]
> If this is as intended, then what should I do to get a mod updated for 1.11

1. Click https://spacedock.info/mod/1931/ToolbarController
2. Locate this alert:
   ![image](https://user-images.githubusercontent.com/1559108/106019837-b5644c00-6088-11eb-8a16-5642a5c6d3b3.png)
3. Click ![image](https://user-images.githubusercontent.com/1559108/106019932-ce6cfd00-6088-11eb-8215-7becc54a5f8b.png)

**Comment by linuxgurugamer** [comment]
ok, thanks.  I try to use Spacedock because it updates immeidately, but I'll look into changing my base dependencies to be on github.

**Comment by HebaruSan** [comment]
Note, the bot is currently in downtime of about 3 hours, investigation ongoing...
