### ISSUE TITLE
[Bug] Updated JanitorsCloset dependency, not yet showing up in CKAN

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8366]
I just pushed an update to the netkan file for The Janitor's Closet, added a new dependency.
#8365 

It passed the checks, I committed it, but after some time (5-10 minutes) it still hasn't shown up in the CKAN exe.  Can you please check to be sure it get merged properly?

Thank you

LGG

**Comment by DasSkelett** [comment]
Well this is interesting.

The indexer first committed the new version, **with** the new dependency,
and two minutes later it committed the it **without** the new dependency, removing it again from the .ckan.

1) https://github.com/KSP-CKAN/CKAN-meta/commit/da58c73a979ed05d9755b84569fddd09a28a3b19
2) https://github.com/KSP-CKAN/CKAN-meta/commit/9869436b4a6cb58d3d9653541e2143d6fa3c818a

This might have been caused by the mod update and the PR happening in such a short time, all while a regular inflation happened.
With the next run in 30 minutes the dependency should get added again.

I guess the indexer picked the messages from the output queue in the wrong order? Although it's a FIFO queue AFAIK, so this shouldn't be possible?

**Comment by DasSkelett** [comment]
As predicted, there's a new commit with the dependency being added again:
https://github.com/KSP-CKAN/CKAN-meta/commit/ed937d15d136778bc82416fda87a0a5ee1bdfe3d

Not closing yet, we might want to figure out how exactly this happened.

**Comment by DasSkelett** [comment]
How it could've happened, after some talking to @techman83:
1) The scheduler starts scheduling it's 30-minute run, using a NetKAN repo checked out before the JC dependency update. This takes some time to go through all netkans.
2) In the meantime, the PR gets merged, and the updated netkan gets sent to the Inbound.fifo queue for the inflator.
3) Now the scheduler arrives at the netkan for JC, and submits it, but still without the new dependency.
4) The inflator fetches the updated netkan from the PR webhook first, and inflates it. It will create a new .ckan for the just released JanitorsCloset version 0.3.7.2, which contains the new dependency, and sends it to the indexer via Outbound.fifo. The indexer indexes it as "added" mod.
5) Now the inflator arrives at the "outdated" netkan from the scheduler. It inflates it, missing the dependency, and sends it to the indexer. The indexer indexes it as "updated" mod, removing the dependency from the existing .ckan.
6) 30 minutes later, the next scheduler run inflates the updated netkan again, making the indexer add the dependency again.

Now somewhere there a webhook notification from SpaceDock should fit in. Maybe it wasn't the scheduler, but the SD webhook that has sent the outdated netkan after the PR webhook. Who knows.

Anyhow, it appears to be a rare race condition between our webhooks and the scheduler. Does someone see an easy fix to prevent this? Otherwise I'd close the issue, since it shouldn't happen very often, and if, it is resolved by the next scheduler run which contains the netkan.

**Comment by HebaruSan** [comment]
- The timestamp between the first two commits was about 3 minutes
- In alphabetical order, JanitorsCloset is 316 out of 908 live netkans in the non-webhook pass (~35%)
- A full inflation pass takes about 10 minutes, 35% of which is 3.5 minutes

So, it does look like the scheduler and the webhook notification were close to simultaneous. That explanation makes sense to me.

> Does someone see an easy fix to prevent this?

Maybe we could revisit duplicate checking in the queues? If they had noticed that we just inflated this mod 3 minutes ago, the second inflation could have been suppressed, and future scheduled runs would have used the latest metadata. But then we would be back to missing _intentional_ duplicates when a mod author uploads several releases in rapid succession.

I'm fine with closing this. :+1:

**Comment by DasSkelett** [comment]
Another idea I got was sending the modification timestamp or current commit hash of the netkan file as message attribute, so the inflator can drop messages if it already inflated the same one but with a newer timestamp/commit hash.
This would still allow updating a netkan file rapidly, and multiple SD releases in a rapid succession (as long as the webhooks have time to process them), but prevent "downgrading" the netkan source.

But Git doesn't preserve the modification time, it's always set to the time you cloned the repo (or pulled commits which changed the files). And the inflator doesn't have a way to compare the commit hashes to find out which one's the newer one AFAIK.
It would also increase IO, memory and mean more state that could introduce new bugs.

So not really preferable over the current situation.

**Comment by linuxgurugamer** [comment]
Sorry to reopen.  First, what should I do the next time I change dependencies?  If I do the update first, then the new dependency will be applied to the older version which it shouldn't.  

Second, it's now 5 hours after I did this, and according to CKAN, still not there.  Is this just a waiting game now?  or should I just do a minor update to the netkan to force a new update?

**Comment by HebaruSan** [comment]
Nah, it's there:
![image](https://user-images.githubusercontent.com/1559108/107983600-bf90b080-6f8b-11eb-8fb5-7c7069ad0ff3.png)

**Comment by HebaruSan** [comment]
As for updating dependencies for a new release, there was outdated metadata for this mod for only 30 minutes, and anyone who installed in that interval would later get a message from CKAN prompting them to reinstall (and pull in the new dep). That's fine for most mods and most users. I don't think you need to change your work flow.

If you want a "perfect" solution, then you will need something that's directly bound to the download file somehow, like version files are. CKAN does have something like that: internal .ckan files. If your ZIP contains a file with a name ending in ".ckan", that file will be parsed as JSON and its contents will be added to the inflated module. For example, my mods do this:

- https://github.com/HebaruSan/PlanningNode/blob/master/GameData/PlanningNode/PlanningNode.ckan

But that's going to be overkill most of the time, and maintaining JSON manually can be tricky without automated validation.

**Comment by linuxgurugamer** [comment]
Thank you.

And I just realized what was happening.  I was looking at the relationships for the older verison, before installing the update.

So yes, it's there, thank you.  

And here's an idea for a small improvement to CKAN.  Maybe some way to say that an update  will require a new dependency???
