### ISSUE TITLE
BDArmory.dll present somewhere under GameData/SourceCode/NextStarIndustries

### ISSUE THREAD

**Issue by ThePixelArtist** [KSP-CKAN/NetKAN#8541]
So i want to install mod called BDarmory but it tells me it was already installed, even tho I never even had that mod on my PC, so I open the file directory it gave me, but it doesnt exist
![CKAN](https://user-images.githubusercontent.com/84506389/118965934-7e80b180-b969-11eb-89ce-357d5a2987ea.png)
![mod directory](https://user-images.githubusercontent.com/84506389/118965945-817ba200-b969-11eb-8a1b-9869b1ef623b.png)
![AD](https://user-images.githubusercontent.com/84506389/118965987-8b9da080-b969-11eb-8dbd-d211fdd34eb2.png)

**Comment by 1Wyatt1** [comment]
Try clicking on the mod and going over to versions on the right side, then select the latest version, this should install it with no issues. If a team member would like to confirm or correct me on this process you're welcome to 😀

**Comment by ThePixelArtist** [comment]
I think im running KSP version 1.11 but i can of course rollback some version as im running KSP though steam

**Comment by ThePixelArtist** [comment]
1. that is not possible since I never even had the BDArmory mod at the first place, I only went in gamedata to clarify that it was indeed not there or delete the DLL if it was there
2. yes I was trying to install the BDarmoryContinued but it was too long to type out so i just said BDarmory

**Comment by DasSkelett** [comment]
>     1. that is not possible since I never even had the BDArmory mod at the first place, I only went in gamedata to clarify that it was indeed not there or delete the DLL if it was there

CKAN doesn't make up imaginary folders in your GameData. At some point the **was** a `SourceCode`  folder in your GameData, which contained a `BDArmory.dll` (or similarly named). Judging from the path, you probably tried to install NextStarIndustries manually, although the image is missing half the error message. All I can say is that whatever mod you tried to install there, but accidentally downloaded the source code instead of the release zip.

Did clicking "Refresh" fix it? If not, you might be looking at the wrong KSP installation (Go to "File > Open game directory") to make sure you open the correct one.

>     2. yes I was trying to install the BDarmoryContinued but it was too long to type out so i just said BDarmory

Doesn't look like it, you screenshot shows `https://spacedock.info/mod/79/BDArmory/download/0.11.0.1` as download source, which is the original outdated BDArmory. YOu can tell that both from the SpaceDock mod id `79`, and the version number `0.11.0.1`.
If you download BDArmoryContinued, you'd probably see `https://github.com/PapaJoesSoup/BDArmory/releases/download/v1.3.4/BDArmory.1.3.4.0_04092020.zip` as download source.

**Comment by ThePixelArtist** [comment]
1. I dont think I tried downloading any mods manually but I can always check that directory (update yes it leads to KSP folder, just not the gamedata but that should be alright)
![CKAN new](https://user-images.githubusercontent.com/84506389/118990655-5c942880-b983-11eb-9c91-194a73b7d93a.png)

2. yes in that screenshot I was trying to install outdated BD as I didnt realise there was a continued version, also the full error message is below

**Comment by DasSkelett** [comment]
Did you click "Refresh" yet?

**Comment by ThePixelArtist** [comment]
Yes

**Comment by DasSkelett** [comment]
Okay. Does BDArmory still show up as "AD"?

**Comment by ThePixelArtist** [comment]
Yes

**Comment by DasSkelett** [comment]
Okay. Then please click on "File > Open game directory", and inside the new explorer window, double-click on GameData. It is important you do this from the window that CKAN opened, and not a separate one you might have already open.
Do you see any folder called `SourceCode` there?

**Comment by ThePixelArtist** [comment]
and in it is this
should I delete it?
![source](https://user-images.githubusercontent.com/84506389/119030301-fa025300-b9a9-11eb-8bfe-fc8da119ee2d.png)

**Comment by DasSkelett** [comment]
Best is you delete the entire `SourceCode` folder, whatever mod this is is from it most likely doesn't belong into GameData.

**Comment by ThePixelArtist** [comment]
alr got it

**Comment by ThePixelArtist** [comment]
Case solved, this appears to be working
