### ISSUE TITLE
Add Contract Pack: Kerbin Space Station

### ISSUE THREAD

**Issue by severedsolo** [KSP-CKAN/NetKAN#860]
Can you add this one please? I am the author.

Netkan file (I hope I did this right): https://github.com/severedsolo/KerbinSpaceStation/blob/master/KerbinSpaceStation.netkan
Forum post: http://forum.kerbalspaceprogram.com/threads/113642-WIP-Contract-Pack-Kerbin-Space-Station
Github: https://github.com/severedsolo/KerbinSpaceStation

**Comment by Dazpoet** [comment]
The .netkan file works but I wonder about the .git stuff in the .zip file. Are those relevant or just there?

Would you mind it if the identifier was changed to ContractConfigurator-KerbinSpaceStation to match the naming scheme of the other Contractpacks?

**Comment by severedsolo** [comment]
No they are irrelevant, I just packaged it badly, will be fixed with the next update (although I'm happy to clean it up now if thats a problem?) - and no problems at all with the changing of the identifier

**Comment by Dazpoet** [comment]
Please clean it up so we don't end up cluttering peoples installs and then I can do a pull request :)

**Comment by severedsolo** [comment]
Thanks - all cleaned up now

**Comment by Dazpoet** [comment]
And then another problem arises I'm afraid. CKAN really likes it when you have a folder to install rather than a bunch of files. I can make a .netkan that will install every file in the current package to /GameData/ContractPacks/KerbinSpaceStation/ but if you make a release with more files in it CKAN won't recognize those ones.

If the files where placed in a folder named e.g. KerbinSpaceStation it will make both of our lives easier since then everything down the road will work automagically rather than having to update the netkan each time a file is added and/or removed and your users will not have to wonder why new contracts aren't showing up :)

**Comment by severedsolo** [comment]
Oh boy, this is what happens when you rush an update out the door 2 minutes before you have to leave for work.

I am so sorry, that is exactly what I intended to do.... I've fixed it now, thanks for your patience.

**Comment by Dazpoet** [comment]
PR merged and the contract pack now shows up in CKAN, closing this issue and look forward to trying out the new contracts :D
