### ISSUE TITLE
Double Hangar Extender mod in repository

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/NetKAN#866]
[HangarExtender.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/HangarExtender.netkan) and [FShangarExtender](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/FShangarExtender.netkan) are the same mod. They have different identifiers but the same name making 2 "Hangar Extenders" show up in the list of mods.

I assume there is no easy fix for this considering https://github.com/KSP-CKAN/CKAN-support/issues/90

If we remove one of them and it causes issues it seems they can be resolved using commandline, see https://github.com/KSP-CKAN/CKAN/issues/746

I'm not sure if there are different mods out there depending on different identifiers for the mod but a simple `provides` should solve that problem.

How are these situations resolved?

**Comment by pjf** [comment]
Well, this is awkward.

The good news is that the only relationship this mod has to anything else is RealismOverhaul, which recommends `FShangarExtender`.

If the GUI can't uninstall unlisted mods, then that's *definitely* a bug. I'm quite certain the command-line can, because that's pretty much what I exclusively use, and I suspect I've more more unlisted mods than anyone. :)

The correct thing to be doing here is remove the duplicate (we probably need not worry about provides, since nothing depends upon it), and fix whatever bug is causing pain in the GUI that prevents unlisted mods from being manipulated.

I may have to prepare a CKAN hack sprint, since I'm pretty sure we've got enough bugs to warrant one. :)
