### ISSUE TITLE
Bad manual install of ModuleManager in extra GameData folder

### ISSUE THREAD

**Issue by needspeed19000** [KSP-CKAN/NetKAN#8931]
Background
----------
* Operating System: Windows 11
* CKAN Version: 1.30.4
* KSP Version: 1.12.1.3142

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No (note: this happend before and after i added the Near Future Propulsion 1.3.5, Near Future Electrical 1.2.3 and Near Future Solar 1.3.2 mods).

Problem
-------
When i trie to update the mods, it all ways fails to do it.

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**
![2021-12-29](https://user-images.githubusercontent.com/96801372/147616055-10318161-4378-4228-adda-088d9b16316c.png)

**CKAN error code (if applicable):**

```Didn't show a code.
PLACE CODE HERE !
```Didn't show a code.

**Comment by HebaruSan** [comment]
This is telling you to delete the extra ModuleManager DLL that you installed. Do that and try again:

![image](https://user-images.githubusercontent.com/1559108/147616374-d1290bfb-ec9f-4bd5-87c8-9f348c50a7fa.png)

But since you have a GameData folder inside your GameData, it's quite possible that there are other serious manual installation problems. That folder should not be there at all.

**Comment by needspeed19000** [comment]
Thank you for resolving my problem because isn't happening anymore.

A quarta, 29/12/2021, 00:18, HebaruSan ***@***.***> escreveu:
