### ISSUE TITLE
PartWizard compatibility information seems wrong for KSP 1.9.1.2788

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/NetKAN#9082]
Background
----------
* Operating System: Windows 7 (yes, I know; no, it isn't)
* CKAN Version: 1.30.4
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No; completely clean install other than using CKAN to install PartWizard and its dependencies. (I did originally observe the issue in a heavily modded 1.9.1).

CKAN offers me PartWizard 1.3.8.3 for KSP 1.9.1. In the VAB, clicking PartWizard's icon tells me "An error has occurred in PartWizard." 1.3.8.2 works as expected.

**Comment by HebaruSan** [comment]
The version file for 1.3.8.3 says:

```json
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 8,
    "PATCH": 0
  }
```

And SpaceDock says:

![image](https://user-images.githubusercontent.com/1559108/164584757-2863a8af-1d71-46e1-85d4-a46e547ec621.png)

And that's what's in the metadata:

```json
    "ksp_version_min": "1.8.0",
    "ksp_version_max": "1.12.1",
```

So it seems to be fine. @linuxgurugamer, was the version file wrong for this version?

**Comment by damerell** [comment]
It does not seem to be fine, since 1.8.0 is less than 1.9.1, but I appreciate it has been fixed upstream.

**Comment by DasSkelett** [comment]
`KSP_VERSION_MIN` means the _minimum_ KSP version, so CKAN's data does match what was in the version file at that time.

**Comment by damerell** [comment]
I understand it means the minimum KSP version; however, since 1.8.0 <= 1.9.1, the effect is that a version of the mod that doesn't work gets installed, and this is not fine. (I appreciate that this is an upstream bug).

**Comment by DasSkelett** [comment]
> the effect is that a version of the mod that doesn't work gets installed, and this is not fine.

The "So it seems to be fine." was in context of CKAN's metadata being correct, which it is, so the metadata is fine.
This is our primary area of concern.

That it doesn't work for you is not fine of course. But before changing the metadata we have to coordinate with the author. Because right now there's no indication that it is actually a compatibility problem (that's just your assumption, maybe a correct one, but still just a guess), it might very well be a different bug.

**Comment by HebaruSan** [comment]
Right; the first thing we check for is, "Did CKAN miss something?" If either the version file or the game version on SpaceDock reflected different compatibility from the CKAN metadata, then it would be easy for us to correct that.

But since all of that data is consistent, we next have to investigate, "Did the _author_ miss something?" This puts us in the position of potentially overriding the will of the author if we guess wrong, which could be bad when users and mod authors will be affected. If we jump to conclusions, then for all we know the next user complaint could be that this version _should_ be compatible with 1.8, so we need to have good evidence if we can find it.

The forum thread says the version file was updated "for 1.12" in 1.3.8.3, which _could_ mean that @linuxgurugamer meant to limit it to KSP 1.12 and up, but he _didn't_ actually do that (see the `KSP_VERSION_MIN` above), and the post doesn't say exactly _how_ he meant to change it, so other interpretations are possible:

![image](https://user-images.githubusercontent.com/1559108/164730307-6cc1409e-98a4-498a-9736-490f815e70b5.png)

The subsequent 1.3.9 version initially doesn't say anything special about compatibility:

![image](https://user-images.githubusercontent.com/1559108/164730397-e62299d6-f2ea-49be-b133-d0a523a97a64.png)

But then a user reported a problem on KSP 1.10, and @linuxgurugamer said it's not supported:

![image](https://user-images.githubusercontent.com/1559108/164730411-6261a793-63d1-4476-b58a-254682f4d3e1.png)

And indeed, we have a commit for that change (replaced the download rather than just uploading the version file, but still):

https://github.com/KSP-CKAN/CKAN-meta/commit/ccb76f49d720315a3ca0aec3e8e3666f53f45162

So it's plausible that some versions before 1.3.9 were similarly affected (it probably wasn't just 1.3.8.3 by itself, if so). We just need to know for sure and which versions. Will continue trying to get a response from @linuxgurugamer.

**Comment by HebaruSan** [comment]
The commits between these two releases are pretty insignificant, which appears to confirm that the break with KSP 1.8 compatibility happened earlier:

https://github.com/linuxgurugamer/PartWizard/compare/1.3.8.3...1.3.9

The transition from 1.3.8.2 to 1.3.8.3 looks more interesting:

https://github.com/linuxgurugamer/PartWizard/compare/1.3.8.2...1.3.8.3

Here we have a change in the `TargetFrameworkVersion` from v4.5 to v4.7.2, which probably did break compatibility with older game versions. And the wiki says KSP 1.12 contained a Unity upgrade:

https://wiki.kerbalspaceprogram.com/wiki/1.12

![image](https://user-images.githubusercontent.com/1559108/164737862-599081f8-7550-4bb8-965e-e75d85cd0848.png)

At this point I'm comfortable updating 1.3.8.3's compatibility. If @linuxgurugamer wants to change it back, he has write access in CKAN-meta.
