### ISSUE TITLE
[Mod] GPOSpeedPump

### ISSUE THREAD

**Issue by Lisias** [KSP-CKAN/NetKAN#9113]
Mod info
--------
* Mod name: Goo Pumps & Oils Speed Pump
* Author(s): hab136, zer0Kerbal, Lisias
* License: GPLv3
* Homepage: https://net-lisias-ksp.github.io/GPOSpeedPump/
* Download: https://spacedock.info/mod/546/Goo%20Pumps%20%26%20Oils%27%20Speed%20Pump%28GPO%29

Hi. Me and zer0Kerbal are tooking over the add'on 546 from SpaceDock, previously known as GPOFuelSpeedPump.

I initially thought I would need to just update the current netkan file but then I found the option "request CKAN" ticked on the configuration page on SpaceDock.

How is the best way to proceed? May I submit a new netkan file without risking screwing up something due that ticked option on SpaceDock? I didn't found it on the CKAN yet, but I don't know if by uploading the new distribution package I would trigger a support ticket fest...

**Comment by DasSkelett** [comment]
The checkbox on SpaceDock generates a new automated pull request, which also auto-detects a few things like install stanza and tags (to some degree), but it seems to be already checked from the past, so you won't be able to re-check it (and no automatic PR is created).
Updating the mod on SD won't do anything on CKAN yet, as all netkans for it are frozen.

So you can submit your own PR if you want. Apparently we had indexed this mod twice at some point: #5073
This one here: https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Goodspeed.frozen
And the other one has been removed here: https://github.com/KSP-CKAN/NetKAN/pull/5140
(And initially accidentally indexed in https://github.com/KSP-CKAN/NetKAN/pull/3656 after the SpaceDock PR https://github.com/KSP-CKAN/NetKAN/pull/3649)

Usually we reuse the existing identifier for continuations, especially if acknowledged by the previous author (since you are co-authors on the old SpaceDock page this is the case).
This would be `Goodspeed` here, which was active for a longer time.
 But since there's probably not many users left over that would benefit of an automatic update to your continuation, a new one (`GPOSpeedPump`) might make sense as well, to have an identifier where we can recognize it again (and not index it a second time again because nobody makes the connection to `Goodspeed`).

**Comment by Lisias** [comment]
SpaceDock was updated, and a pull request to netkan was applied!

https://github.com/KSP-CKAN/NetKAN/pull/9120

Thanks!
