### ISSUE TITLE
Non-breaking spaces in Starship Launch Expansion short description on SpaceDock

### ISSUE THREAD

**Issue by SAMCG14** [KSP-CKAN/NetKAN#9145]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

Problem
-------
The Starship Launch Expansion description have some "?" in the middle of the text.

![image](https://user-images.githubusercontent.com/67849318/171462593-6000f717-8e61-475d-948d-99bfdd7c28c0.png)

It should appear like this:
Starship Launch Expansion is a mod that collects Starbase real life launch pads, towers, stands and all the stuff necessary to support your Starship launches in KSP. All the parts are designed to withstand the power of every launch without exploding (hopefully).

**Comment by HebaruSan** [comment]
Hi, those characters are on SpaceDock (they're the [`\u00a0`](https://www.fileformat.info/info/unicode/char/00a0/index.htm)):

https://spacedock.info/api/mod/2814

![image](https://user-images.githubusercontent.com/1559108/171465095-708048ba-e2d4-4145-beb5-1f982983b441.png)

Try removing them to fix this.

**Comment by HebaruSan** [comment]
Some further details, these are "no-break spaces," which look like spaces but prevent word wrap from occurring at that location. You can see this effect in action by changing the width of your browser to try to make the short description wrap at various places. For example:

![image](https://user-images.githubusercontent.com/1559108/171487000-c22bd92f-ea7c-4f78-a108-4d5b32109616.png)

Slightly narrower, instead of wrapping between "life" and "launch", the first line wraps after "real":

![image](https://user-images.githubusercontent.com/1559108/171487088-fef9b586-705a-4c71-a766-97e628aae048.png)

**Comment by HebaruSan** [comment]
Hopefully that explanation is sufficient. Please let us know if you have further questions.
