### ISSUE TITLE
Ven Stock-Revamp mod isn't updated on CKAN

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN#924]
SVlad mentioned on [forum](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-6-26-Mar-2015?p=1829561&viewfull=1#post1829561) that Ven Stock-Revamp mod isn't updated on CKAN. I tried to fix this but somethings is really weird. There is [.ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/VenStockRevamp/VenStockRevamp-1.7.2.ckan) for new 1.7.2 version but when I try to install it this happens:
```
ckan install -c VenStockRevamp-1.7.2.ckan 
About to install...

 * VenStockRevamp v1.7.1
 * ModuleManager 2.6.0

```
Any ideas/help how to fix this?

**Comment by TeddyDD** [comment]
Ok, probably its because string "v1.7.1" is > "1.7.2" 
I'm thinking how to fix this

**Comment by NathanKell** [comment]
I made a fresh v1.7.2 release of Ven's Stock Revamp to get around this issue. Has it been fixed?

**Comment by pjf** [comment]
Oh! I remember asking for this on the forums ages ago. @NathanKell , I didn't realise you had release permissions. :)

Yes, this fixes things, even if it doesn't look like it because the bot appears to have stopped again. (I'm still doing handover with @AlexanderDzhoganov on that).

I'll push a manual update now.
