### ISSUE TITLE
ksp.marce.at has been taken down, mods stuck in limbo

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/NetKAN#932]
Mods created by Marce have been halted and removed from the webpage in the heading. This leaves the mods in limbo with nowhere to be downloaded from. Reason can be found [here](http://forum.kerbalspaceprogram.com/threads/95865-DEV-HALTED-Caelum-Ire-Technologies-%28CIT%29-General-Thread?p=1820738&viewfull=1#post1820738) so I don't expect the mods to return shortly nor at all for the forseeable future.

Mods are not available through KS nor any other alternate mirror that I could find in a short time of searching nor do I think the author would welcome an alternate download solution based on the linked post above.

As we lack a means of depreciation how are cases like these handled?

**Comment by TeddyDD** [comment]
If any external mod depends on Marce's mods we are fu****
If no, I think we can remove packages. I think (but I'm not sure) they just become "unknown" for users that already have them installed :warning: I'm not really sure :warning: 

Also look here https://github.com/KSP-CKAN/CKAN-meta/search?utf8=%E2%9C%93&q=deprecated
ContractConfigurator-SCANsat was just renamed
(btw.  WTF is ``` "version": "Deprecated",``` ?)

**Comment by pjf** [comment]
So, the good news is that as far as I can tell all of Marce's mods have been released under licenses that permit redistribution ([CC-BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)). That explicitly gives irrevocable permission to modify and distribute the work as long as we comply with the license terms. Licenses are important because they're assurances to users that even if the author changes their mind later on, the users can continue to use, distribute, and maintain the software as required. 

The other good news is that we'll have multiple copies of any mod that permits redistribution as part of the MirrorKAN network, so recovering these mods from the abyss *should* be a straightforward process.

From a technical and legal standpoint, we're 100% fine in making these available from the CKAN, and having new developers take over their maintenance.

The sticky points here are *social* ones, although ones that have been encountered *many* times before by the free software community. Our first steps are gathering information as to what has happened, seeing of Marce has a change of mind, and then assessing the impact and outcomes of our options.

**Comment by marce155** [comment]
I forgot about CKAN, should have notified you guys, sorry.
It is true that you have the legal rights to continue my work. I have been burned by oss and will not make such a mistake again, but that’s not your problem. Good luck finding a maintainer, though. I searched for about 2 months without success. Since I’m now seriously pissed I ended the search and put my work down. 
I deleted the source code on purpose to require a decompile and make it harder. Why? Because only a serious person with a little skill should continue my work. If you find such a person I’ll be happy, but I doubt it.
The good news is: ActiveStruts has been handed over to the IR team and will be maintained. All my other mods have so few users that not a single complaint or even question has been received. No trouble here.
Take it as a good chance to improve your system with a removal feature :)

**Comment by Dazpoet** [comment]
Seems at least one person [noticed](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-(CKAN)-Package-Manager-v1-6-6-26-Mar-2015/page92?p=1832945#post1832945).

But yes a removal/depreciation feature would be pretty awesome but is a discussion for another place :)

**Comment by Dazpoet** [comment]
So some mods seem to be affected by this. I did an ugly hack and used the redistributed activestruts and cit-util folders in IR-Model-Rework-Utility to get it working and set it to conflict with those mods should we get them back online.

As is reported [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-10-20-Apr-2015?p=1856168&viewfull=1#post1856168) MissionController2 is also affected by `KERT` no longer being available.

**Comment by plague006** [comment]
There's been nothing in 3 months. I *think* we can close this and address any further issues as they arise?
If anyone feels I'm closing this prematurely I'll happily reopen.

**Comment by Dazpoet** [comment]
This might turn interesting once the IR utility stuffs get an update, but it's linked from within the .netkan file so I guess whoever runs into that issue down the line will find their way here.

**Comment by HebaruSan** [comment]
The updated link to the forum post as of this writing appears to be:

https://forum.kerbalspaceprogram.com/index.php?/topic/86456-dev-halted-caelum-ire-technologies-cit-general-thread/&do=findComment&comment=1805406
