### ISSUE TITLE
GPP conflicts with new Scatterer releases

### ISSUE THREAD

**Issue by fyggy** [KSP-CKAN/NetKAN#9331]
Background
----------
* Operating System: Windows 10 Pro 10.0.19043 Build 19043
* CKAN Version: CKAN v1.31.0
* KSP Version: KSP 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes - Manually installed Scatterer 3:v0.0825b

Problem
-------
**Describe the bug**
CKAN says that Scatterer conflicts with GPP 1:1.6.8.0, a planet expansion pack. However, after installing manually, I found that this was not true; Scatterer performed perfectly with no (discernable) bugs or errors. However, this means that now CKAN refuses to install any new mods in the instance. I belive this to be a simple error in compatability metadata

**Steps to reproduce**
Install GPP 1:1.6.8.0, then attempt to install Scatterer (any version).
Alternativly, GPP 1:1.6.8.0, then manually install Scatterer 3:v0.0825b, then attempt to install any mod using CKAN

**Expected behavior**
CKAN should allow the installation of Scatterer while using GPP, as the mods are compatabile.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Hey, it's only the v0.08xx versions of Scatterer that conflict with GPP, because they had breaking changes which the GPP config hasn't been adjusted for yet. If you install a v0.07xx version of Scatterer, e.g. using the "Versions" tab on the right, you'll be able to install it with GPP.

Release notes and mod author comments still say this conflict exists:
https://github.com/Galileo88/Galileos-Planet-Pack/releases/tag/1.6.8.0
> **Known Issues**
This planet pack is not compatible with Scatterer v0.0825b, use v0.0772.

https://forum.kerbalspaceprogram.com/index.php?/topic/152136-ksp-1121-galileos-planet-pack-v166-23-sept-2021/&do=findComment&comment=4168574
> For Scatterer we recommend v0.0772 (GPP has not been updated for v0.08x).
