### ISSUE TITLE
Utility Uplift Mod Zip file Corrupted

### ISSUE THREAD

**Issue by Yeetster-cmd** [KSP-CKAN/NetKAN#9656]
I have been told (and have confirmed) a bug with one of the zip's regarding a KSP2 Mod. This would be Utility Uplift, from what I can tell from the error message, the zip file on the CKAN server seems to be corrupted. This has happened to 3 people, but those are just the ones who have reported it. This bug does not appear when downloading the zip from Spacedock, so that's why I and a few other people though it was a corrupted zip on the CKAN server.

Error Message:
``CKAN.InvalidModuleFileKraken: UtilityUplift 1.0.2: C:\Users\TheYeetster\AppData\Local\CKAN\downloads\downloading\5A112C2B-UtilityUplift-1.0.2.zip has length 210420, should be 247430
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move, CancellationToken cancelToken)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)``

**Comment by HebaruSan** [comment]
Hi, that's not saying it's corrupted, it's saying the file is different from what the bot saw when it added that release. That happens when the mod author uploads a release, then CKAN adds it, then the author deletes it and re-uploads a different file with the same version. The bot will catch up eventually.

**Comment by Yeetster-cmd** [comment]
Alright, thank you for your quick response!
