### ISSUE TITLE
[Bug]: MoarKerbalsParts does not install MoarKerbals as a dependency. 

### ISSUE THREAD

**Issue by heyimastopsign** [KSP-CKAN/NetKAN#9915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### CKAN Version

1.34.2

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

The MoarKerbalsParts mod creates parts designed specifically for MoarKerbals, but in spite of this does not install MoarKerbals itself. This results in the mod instead adding a bunch of fairly expensive decorative crew containers.

<img width="563" alt="Screenshot 2024-01-31 at 11 44 03 am" src="https://github.com/KSP-CKAN/NetKAN/assets/139853723/b04a696d-3964-4477-b59f-00f78305cf4a">
<img width="166" alt="Screenshot_2024-01-16_at_9 14 34_pm" src="https://github.com/KSP-CKAN/NetKAN/assets/139853723/4992ba5b-fd7c-4b83-9e0d-bbd1bee4cd45">

### Steps to reproduce

* Install MoarKerbalsParts, note the lack of dependencies
* Launch a ship with any part from the mod, as well as any necessary power and crew
* When attempting usage of any of the aforementioned parts, the option to begin Kloning, Kuddling, etc is not present

**Comment by HebaruSan** [comment]
Hi @heyimastopsign, thanks for the report. This is intentional and correct, because the mod listing says specifically that it is a recommendation and not a requirement:

- <https://spacedock.info/mod/2898/MoarKerbalsParts>

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/331f021c-7e43-4375-aea1-fce81b156074)
