### ISSUE TITLE
Author removed 4 mods from net, still listed on CKAN

### ISSUE THREAD

**Issue by jvsperoni** [KSP-CKAN/NetKAN#9919]
I'm submitting this issue because I don't know another way to delist mods from CKAN. Note that I am not the owner of any of these mods but it seems obvious that the owner deliberately took down their content.

"Sunnypunny" has 4 mods on CKAN. Downloads and other links are dead because the owner removed repositories. Related KSP forum threads exist but sunnypunny deleted their old posts and threads are locked. Those mods are:

OpenTree
FacilityTree
KerbalHero
KerbalWitchery

**Comment by JonnyOThan** [comment]
Thanks for the heads up.  All 4 of these mods are published with a permissive licence (MIT).  When mods are listed in CKAN with licenses that allow for redistribution, CKAN will make a backup copy of them on archive.org in case the original hosting is unavailable (usually due to temporary technical problems).  This provides a much smoother experience for CKAN users.  So as of now, these mods are still available on CKAN.

As it says in our [indexing policy](https://github.com/KSP-CKAN/CKAN/blob/master/policy/indexing.md) we honor all requests from authors to de-list their content.  If sunnypunny gets in touch with us and asks us for the mods to be removed from CKAN, we'd do it - but for hopefully obvious reasons we won't do that if a 3rd party requests it.
