### ISSUE TITLE
Add Cryo Engines Restock and Cryo Engines NFLV

### ISSUE THREAD

**Issue by ABCGrape** [KSP-CKAN/NetKAN#9969]
https://github.com/post-kerbin-mining-corporation/CryoEngines/blob/master/CKAN/CryoEngines-Restock.netkan
https://github.com/post-kerbin-mining-corporation/CryoEngines/blob/master/CKAN/CryoEngines-NFLV.netkan

These are optional patches for CryoEngines. They are listed in the original repository but not indexed on CKAN.

**Comment by HebaruSan** [comment]
Hey @ChrisAdderley, are these (CryoEngines-Restock and CryoEngines-NFLV) ready to be added to CKAN? I notice they were left out when you submitted #7157, but without your word we can only guess whether that was intentional. (The CryoEngines-NFLV netkan also has an error, so it would need some updating to be usable.)

Thanks!

**Comment by HebaruSan** [comment]
No response from author, closing.

@ABCGrape, if you are able to get in touch with Nertea and confirm that it's OK with him to add these, please let us know and we can re-open this.
