### ISSUE TITLE
[Mod]: My-KSP-Patches

### ISSUE THREAD

**Issue by ProgrammerFailure** [KSP-CKAN/NetKAN#9990]
### Mod Name

My-KSP-Patches

### Author(s)

Me

### License

Unlicense license

### Homepage link

https://github.com/ProgrammerFailure/My-KSP-patches

### Download link

https://github.com/ProgrammerFailure/My-KSP-patches/releases

**Comment by ProgrammerFailure** [comment]
This mod is mainly a set of patches I use a lot in KSP. Wanted it in CKAN so I could manage its versions (I plan to add a few different versions)
It depends on module manager.

It supports:
Sandcastle: https://forum.kerbalspaceprogram.com/topic/201137-min-ksp-112x-sandcastle-3d-printing-for-parts-and-vessels/
Wild blue tools: https://github.com/Angel-125/WildBlueTools
Mechjeb2: https://forum.kerbalspaceprogram.com/topic/154834-112x-anatid-robotics-mumech-mechjeb-autopilot-2143-4th-march-2023/
Procedural parts: https://forum.kerbalspaceprogram.com/index.php?/topic/204080-*
Scansat: https://forum.kerbalspaceprogram.com/index.php?/topic/72679-1
Throttle controlled avionics: http://forum.kerbalspaceprogram.com/index.php?/topic/97154-throttle-controlled-avionics
Extraplanetary launchpads: https://forum.kerbalspaceprogram.com/index.php?/topic/54284-*
Kerbal Inventory System: http://forum.kerbalspaceprogram.com/index.php?/topic/149848-kerbal-inventory-system-kis
Moar station science: https://forum.kerbalspaceprogram.com/index.php?/topic/200041-110x-111x-moar-station-science/
Community Resource Pack: https://forum.kerbalspaceprogram.com/index.php?/topic/83007-*
MKS: https://forum.kerbalspaceprogram.com/index.php?/topic/154587-*

And also all Wild Blue Industries/Angel-125 mods. 

Question: if I make a separate branch for a slightly different purpose, should I make it a version or add it as a new mod to CKAN?

**Comment by HebaruSan** [comment]
@ProgrammerFailure, if other users are going to see this and have the option of installing it, can you please give it a name that expresses what it is and does? "My KSP Patches" will only make sense for you since they aren't anyone else's patches.

**Comment by ProgrammerFailure** [comment]
What about something like: ProgrammerFailure's mod adjustments?

**Comment by ProgrammerFailure** [comment]
@HebaruSan 
Would "ProgrammerFailure's mod adjustments" be sufficient?
Anything else I need to add?

**Comment by ProgrammerFailure** [comment]
Sorry, closed on accident

**Comment by ProgrammerFailure** [comment]
@HebaruSan 
Any updates on this?

**Comment by HebaruSan** [comment]
Hi @ProgrammerFailure, it seems like this is just your personal collection of random patches rather than an actual coherent **mod** that others might want to use. That's not really what CKAN is for; we would not want to clutter _every_ user's mod list with entries that apply to just one single user.

If you're sure that CKAN metadata would be useful for you (rather than just using version control in a folder on your disk), one option would be:

1. Create your own [`My-KSP-Patches.netkan`](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#advanced) file
2. Inflate it with [`netkan.exe`](https://ksp-ckan.s3-us-west-2.amazonaws.com/netkan.exe) to generate `.ckan` files when it changes
3. Place them in your own custom metadata repo (equivalent to [CKAN-meta](https://github.com/KSP-CKAN/CKAN-meta), where the metadata goes for mods that are for all users)
4. Add that to your CKAN instance in the settings

That way you could use CKAN to install/upgrade/remove it as you please, without needing to added it to the main list of mods.

**Comment by ProgrammerFailure** [comment]
@HebaruSan can you explain a little more? I made a netkan file with the webtool, what do you mean by inflate it?
